### ISSUE TITLE
选择雀魂的直接没下一步了

### ISSUE THREAD

**Issue by zhengye1** [EndlessCheng/mahjong-helper#100]
Chrome的版本
Version 87.0.4280.88 (Official Build) (64-bit)

Header Editor 开启了，甚至连CORS Unblocker都开了
![image](https://user-images.githubusercontent.com/5428784/102039500-026db680-3d98-11eb-9f08-d3c3b5a6a63c.png)
但是无论是日服都好还是国际服都好，我是在cmd打开exe文件，选择1-雀魂，然后下一步就成了这样
![image](https://user-images.githubusercontent.com/5428784/102039533-216c4880-3d98-11eb-8dbd-dda8af5cde25.png)
刷新游戏后没有任何变化...，已经清除掉了cookies
甚至把电脑管家关闭后在刷新游戏一样的...怎么解决啊？

**Comment by ttys001** [comment]
应该是雀魂更新后，助手脚本还没更新吧，等等吧。好多次了，我也想学学怎么自己改脚本，不然经常更新后就没法用了

**Comment by EndlessCheng** [comment]
> 应该是雀魂更新后，助手脚本还没更新吧，等等吧。好多次了，我也想学学怎么自己改脚本，不然经常更新后就没法用了

这个问题可以清除缓存来解决。我先 close 了，如果后面有不同于此的问题可以开新的 issue。
