### ISSUE TITLE
与Avenshy / majsoul_mod_plus一同使用的时候无法读取自风

### ISSUE THREAD

**Issue by Moeblack** [EndlessCheng/mahjong-helper#103]
如题所示，猜想是header editor的自风获取与该插件冲突

插件地址 https://github.com/Avenshy/majsoul_mod_plus

**Comment by Moeblack** [comment]
查看代码后发现是此插件将对局中传输给local_server的Acountid屏蔽导致无法获取GetSelfSeat,请求加入手动切换当前座位功能

**Comment by Moeblack** [comment]
已自行修复

**Comment by ANPULI** [comment]
遇到了相同的问题，感谢老哥解决。考虑给原repo提个PR吗？

**Comment by Avenshy** [comment]
已更新，感谢~
