### ISSUE TITLE
一直顯示echo: http: TLS handshake error from [::1]:數字: remote error: tls: unknown certificate

### ISSUE THREAD

**Issue by notebook855171** [EndlessCheng/mahjong-helper#107]
我清空了Cookie後還是這樣顯示
![image](https://user-images.githubusercontent.com/77668788/105020460-484a2880-5a82-11eb-88a0-a99e799e4b15.png)

**Comment by EndlessCheng** [comment]
见 #71  和 #104。
如有问题，请在 #71  下反馈。
