### ISSUE TITLE
chrome浏览器最新的88版本没有 chrome://flags/#allow-insecure-localhost 选项了

### ISSUE THREAD

**Issue by sumneko** [EndlessCheng/mahjong-helper#108]
有什么替代选项吗？

**Comment by sumneko** [comment]
查了下是 chrome 的bug，只能等他们修复了

**Comment by cuteJaven** [comment]
I found a solution:

1. Launch chrome://flags/#temporary-unexpire-flags-m87 on address bar
2. Set to Enabled
3. Re-launch
4. Launch chrome://flags/#allow-insecure-localhost on address bar
5. Now visible, set to Enable
6. Re-launch
