### ISSUE TITLE
浏览器输入chrome://flags/#allow-insecure-localhost后没有对应的设置项

### ISSUE THREAD

**Issue by Crimson19** [EndlessCheng/mahjong-helper#109]
在浏览器地址栏中输入 chrome://flags/#allow-insecure-localhost 后，没有找到Allow invalid certificates for resources loaded from localhost这一项   
![QQ截图20210127184328](https://user-images.githubusercontent.com/34568243/105980542-f59aed00-60cf-11eb-8c61-c71badca97b2.png)

**Comment by EndlessCheng** [comment]
参考 #108
