### ISSUE TITLE
雀魂协议

### ISSUE THREAD

**Issue by luqigit** [EndlessCheng/mahjong-helper#11]
雀魂协议 使用 protobuff 
    具体message https://majsoul.union-game.com/0/v0.4.243.w/res/proto/liqi.json

**Comment by luqigit** [comment]
我对golang 不熟悉
不清楚golang有没有 根据 liqi.json 生成proto 的方法
如果根据liqi.json 手动编写proto 太复杂

**Comment by EndlessCheng** [comment]
@luqigit  请问你整理的雀魂协议中的那些实际数据是怎么得到的？我看了下雀魂的源码，没找到合适的获取数据的地方

**Comment by luqigit** [comment]
2. 在该函数末尾添加如下代码（注意地址是 HTTPS 协议）

var req = new XMLHttpRequest();
req.open("POST", "https://localhost:12121/");
req.send(e.data);
GameMgr._inRelease = 0;

**Comment by luqigit** [comment]
然后看console

**Comment by EndlessCheng** [comment]
@luqigit 这样啊，开启 debug 模式后容易了不少

**Comment by luqigit** [comment]
@EndlessCheng  还是要分析协议  这个只能看数据

**Comment by EndlessCheng** [comment]
我在几个关键的地方注入了代码（见 README），拿到了 JSON 化的数据
直接解析 JSON 数据就行了
