### ISSUE TITLE
一直需要删Cookie重登录

### ISSUE THREAD

**Issue by Irkallaxeynox** [EndlessCheng/mahjong-helper#113]
一直需要不断地删Cookie重新登陆才能继续使用。
浏览器：Chrome Latest
不然还是显示TLS Handshake Error.

另：在可见的未来，考虑开放维基编辑吗？

新手帮助：
1. Edge可以用，但Chrome更方便。Firefox似乎用不了。
2. 把杀软关掉。火绒的HIPS规则加了一大堆但好像还是会拦截。Windows Defender应该也要关掉。
3. 待机一阵后可以点击牌谱（雀魂）来检查助手是否还活着。
4. 先开助手再登网页。

**Comment by EndlessCheng** [comment]
维基编辑是什么内容呢

**Comment by Irkallaxeynox** [comment]
维基是Github项目页的Wiki
内容大概就是一些关于常见的问题的排查，issue#71好像很难解决全部问题……

**Comment by EndlessCheng** [comment]
我刚才修复了一下 Cookie 的问题，麻烦再删除一次 Cookie 后试试，应该后续不需要删了。

你说的这些帮助信息我整合一下，感谢整理。

**Comment by Irkallaxeynox** [comment]
感谢！目前v0.2.8的release可以用了，解决了Cookie的问题。
之前遇到一个问题，如果加载游戏使用中文繁体（中文国际服）的时候在偏好设置中切换为简体中文并游戏内立即重启后大概率需要重新删Cookie登录，现在也解决了。
