### ISSUE TITLE
使用助手后无法切换到中文

### ISSUE THREAD

**Issue by lordleonli** [EndlessCheng/mahjong-helper#116]
天凤已经支持中文了，可是使用Header Editor扩展后切换语音里只有日文和英文。

**Comment by EndlessCheng** [comment]
感谢反馈。

已经更新至最新版，请刷新网页。

**Comment by lordleonli** [comment]
> 感谢反馈。
> 
> 已经更新至最新版本，请刷新网页。

作者君太可爱了，已经可以正常显示了。
