### ISSUE TITLE
試了所有的解決方法都進不了遊戲

### ISSUE THREAD

**Issue by Yin-Xue** [EndlessCheng/mahjong-helper#117]
![image](https://user-images.githubusercontent.com/81866735/113481660-54645480-94cd-11eb-8e6d-934122fce9c7.png)
 關了Extension後，能正常進遊戲

**Comment by EndlessCheng** [comment]
1. 请确认截图中的 code-zh.js 是否下载完毕，我看你这个文件下载了很久；
2. 我注意到你用到了其他插件（雀魂mod_plus），请尝试关闭其他插件后使用。

**Comment by Yin-Xue** [comment]
已經好了，不是插件的問題，花了30分鐘來下載。(ノ｀Д)ノ
