### ISSUE TITLE
路线 获取失败

### ISSUE THREAD

**Issue by Yin-Xue** [EndlessCheng/mahjong-helper#118]
![Snipaste_2021-04-22_22-02-43](https://user-images.githubusercontent.com/81866735/115728193-dd78f800-a3b6-11eb-827a-b2631ee14e42.png)

**Comment by EndlessCheng** [comment]
我刚才试了一下是可以获取的，你能确认这个问题是开启 Header Editor 导致的吗？

**Comment by Yin-Xue** [comment]
是的

**Comment by EndlessCheng** [comment]
我注意到你使用了一些插件：雀魂mod_plus，请关闭后刷新看看。

**Comment by Yin-Xue** [comment]
Hard Reload 後又能連了
