### ISSUE TITLE
雀魂中的部分bug

### ISSUE THREAD

**Issue by endlessWar** [EndlessCheng/mahjong-helper#12]
1.起始位为南，程序当成起始位为北，导致对家显示为我的舍张；
2.全场的副露都算作了我的副露，导致我手牌非常长；
3.因为1，所以当我副露过多时，会提示我的安牌，对家立直时不会提示安牌

**Comment by EndlessCheng** [comment]
你编译的版本是什么时候的？较早的代码可能有这个bug

**Comment by EndlessCheng** [comment]
找到问题了，请重新编译程序
