### ISSUE TITLE
Mac M1 无法使用

### ISSUE THREAD

**Issue by jianhuig** [EndlessCheng/mahjong-helper#120]
如题

**Comment by EndlessCheng** [comment]
我单独编译了一个文件，请试一下能否正常运行。

需要用终端打开，可能需要修改执行权限。

[mahjong-helper-v0.2.8-mac-m1.zip](https://github.com/EndlessCheng/mahjong-helper/files/6463188/mahjong-helper-v0.2.8-mac-m1.zip)

**Comment by jianhuig** [comment]
还是不行哦，我在终端里输入
open mahjong-helper-v0.2.8-mac-m1
打开的是txt乱码

**Comment by EndlessCheng** [comment]
你需要解压出来，得到 `mahjong-helper-mac-m1` 文件。

打开的话可以用 `./mahjong-helper-mac-m1` 试试。

**Comment by jianhuig** [comment]
刚刚打错了，我已经解压过了。
chmod +x ./mahjong-helper-mac-m1 
可以正常运行，谢谢。
