### ISSUE TITLE
net : : ERR_CONNECTION_RESET 200 ( OK )

### ISSUE THREAD

**Issue by Yin-Xue** [EndlessCheng/mahjong-helper#122]
![Snipaste_2021-05-23_11-46-39](https://user-images.githubusercontent.com/81866735/119247578-378afa00-bbbd-11eb-9b44-733c4b9cb186.png)
CORS Unblock 已装
![Snipaste_2021-05-23_19-47-23](https://user-images.githubusercontent.com/81866735/119259218-c7ea2e80-bbff-11eb-945a-45d7fc35f4fb.png)

**Comment by EndlessCheng** [comment]
请尝试 #104  中提到的方法

**Comment by Yin-Xue** [comment]
已自行修复
