### ISSUE TITLE
header editor启用时雀魂黑屏

### ISSUE THREAD

**Issue by oc-create** [EndlessCheng/mahjong-helper#128]
code-zh.js报错导致黑屏 无法打开登陆界面
![QQ图片20210710130334](https://user-images.githubusercontent.com/51143069/125170957-96adc980-e17f-11eb-9333-4c2ee4386f05.png)

**Comment by EndlessCheng** [comment]
请参考 #125 ，如未能有问题请在下方回复

**Comment by oc-create** [comment]
感谢 问题已解决 
海外连接gitee存在一定困难
