### ISSUE TITLE
最後 清空缓存并进行硬刷新 黑畫面。

### ISSUE THREAD

**Issue by paradoja20000628** [EndlessCheng/mahjong-helper#132]
![image](https://user-images.githubusercontent.com/86232535/132091075-2092871f-9f1b-4826-8964-8ee4480d162a.png)

**Comment by EndlessCheng** [comment]
我同步了雀魂最新版本，麻烦再看看是否还有这一问题。

**Comment by EndlessCheng** [comment]
还有可能是在下载 `code-zh.js` 文件，你可以在开发者工具中的 `网络` 标签下查看。

**Comment by paradoja20000628** [comment]
![image](https://user-images.githubusercontent.com/86232535/133011582-034d20fc-acec-4d11-a1e9-b2d98f3e169b.png)

**Comment by paradoja20000628** [comment]
這個嗎?

**Comment by paradoja20000628** [comment]
> 還有可能是在下載`code-zh.js`文件，你可以在開發者工具中的`网络`標籤下查看。

似乎卡住了 如何解決? 他卡的挺久的

**Comment by EndlessCheng** [comment]
见 #125

**Comment by paradoja20000628** [comment]
GitHub Pages 如何創建?

**Comment by EndlessCheng** [comment]
请搜索相关教程

**Comment by paradoja20000628** [comment]
vpn似乎比較簡單 我在台灣 vpn要連哪個國家呢
