### ISSUE TITLE
都設置好了最後跑出https://localhost:12121/ net::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by qaqa960123** [EndlessCheng/mahjong-helper#133]
看這個不是用這個的嗎chrome://flags/#allow-insecure-localhost 我其他都用好了console卻一直跑出https://localhost:12121/ net::ERR_CERT_AUTHORITY_INVALID

**Comment by EndlessCheng** [comment]
设置好之后你有重启浏览器吗？
