### ISSUE TITLE
分析正常，但只要有任何人和牌就会卡死

### ISSUE THREAD

**Issue by OKURBITO** [EndlessCheng/mahjong-helper#134]
![QQ截图20210911135625](https://user-images.githubusercontent.com/31618916/132999647-3ff25dfe-5b1c-431f-957e-d8c372b876e8.png)
错误代码如上，大概有90%以上的几率和牌卡死，已经尝试清除缓存，重新载入json文件，没有效果

完整的错误代码如下
Uncaught TypeError: Cannot read properties of undefined (reading 'hp')
    at l.defeatAll (code.js:125)
    at e.show (code.js:136)
    at r._showInfo_mj (code.js:136)
    at r._showHule (code.js:137)
    at r.show (code.js:136)
    at n.ShowWin (code.js:57)
    at Function.<anonymous> (code.js:67)
    at t.e.run (code.js:5)
    at t.n._update (code.js:5)
    at e.o.render (code.js:8)

requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3
requestAnimationFrame(异步)		
a	@	code.js:3

**Comment by EndlessCheng** [comment]
我同步了雀魂最新版本，麻烦再看看是否还有这一问题。

**Comment by OKURBITO** [comment]
> 我同步了雀魂最新版本，麻烦再看看是否还有这一问题。

谢谢大佬，已解决问题
