### ISSUE TITLE
界面全黑，console显示"mixed content" error

### ISSUE THREAD

**Issue by zhuoyw** [EndlessCheng/mahjong-helper#135]
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/5935782/139206304-c1c335e1-778a-444f-b673-d00abd8f8748.png">

为啥是jianyan.me 这个url？

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/5935782/139206423-3624f6f1-9d48-4c64-a268-6c0342cc8b70.png">

header editor这里是对的。

提前感谢！

**Comment by EndlessCheng** [comment]
我更新了链接，麻烦从 `https://mjhelper.github.io/mahjong-helper.json` 中下载重定向规则。
