### ISSUE TITLE
卡在初始界面

### ISSUE THREAD

**Issue by hugplz** [EndlessCheng/mahjong-helper#136]
![20211030100539](https://user-images.githubusercontent.com/93414548/139516724-853e48a2-c272-4541-86d5-58cf1e615ef7.png)

**Comment by EndlessCheng** [comment]
设置好后有重启浏览器吗？

**Comment by EndlessCheng** [comment]
可以试试 #104 的方法

**Comment by hugplz** [comment]
> 可以试试 #104 的方法

OK了，我重启了一遍助手，谢谢老哥
