### ISSUE TITLE
[Enhancement] 新协议的支持 - FFXIV

### ISSUE THREAD

**Issue by Bluefissure** [EndlessCheng/mahjong-helper#137]
程学长好久不见！缘分真是妙不可言！

最近有群友向我询问能否将本项目应用到 最终幻想14（Final Fantasy XIV） 里面的金蝶游乐场中的日麻小游戏。虽然我没打过日麻，不是很了解游戏的机制，但是居其所说大部分的规则是一样的，所以本着不重复造轮子的想法在考虑能不能写一个游戏内的插件通过 WS 和本项目通讯。

考虑到我的十八手 GoLang 水平和没太完善的开发文档（？）想知道相关的协议解析能够参考哪部分的代码？或者有没有什么建议/例子能够参考？

**Comment by EndlessCheng** [comment]
私信交流哦
