### ISSUE TITLE
雀魂自风判断问题

### ISSUE THREAD

**Issue by endlessWar** [EndlessCheng/mahjong-helper#14]
雀魂部分房间仍然有自风判断错误的问题，如金南
![r6i 5o n qq9 h6_3gqcf](https://user-images.githubusercontent.com/47861644/53615771-7cac6580-3c1a-11e9-896a-ff97bd9268c1.png)
![6owl2s q f8 abh t85y](https://user-images.githubusercontent.com/47861644/53615773-7fa75600-3c1a-11e9-8874-e0d2649cec44.png)

![image](https://user-images.githubusercontent.com/47861644/53615792-951c8000-3c1a-11e9-85d7-23f073d478d6.png)

**Comment by EndlessCheng** [comment]
我最近加入了获取玩家账号ID的方式，你用的是这个版本吗？

**Comment by endlessWar** [comment]
> 我最近加入了获取玩家账号ID的方式，你用的是这个版本吗？

是的，友人和人机是没有问题的
但是金南就会出现这样的问题

**Comment by EndlessCheng** [comment]
你用的这个版本是什么时候编译的？

**Comment by endlessWar** [comment]
刚刚测试金东，出现了一样的问题
获取编译时间为今天中午

**Comment by EndlessCheng** [comment]
我找到问题了，你是否在程序启动后换了几个账号？

**Comment by endlessWar** [comment]
> 我找到问题了，你是否在程序启动后换了几个账号？

并没有，只用了一个账号

**Comment by EndlessCheng** [comment]
在程序启动后，选择雀魂，刷新网页，是否有打印账号 ID？

**Comment by EndlessCheng** [comment]
PS 目前程序还未支持对战中的重连

**Comment by endlessWar** [comment]
> 在程序启动后，选择雀魂，刷新网页，是否有打印账号 ID？

是的，打印了账号，并提示，账号数字越小，账号创建越早

并未重连

**Comment by endlessWar** [comment]
这个问题是随机出现的又开了一把金东，好了

**Comment by EndlessCheng** [comment]
我刚才加了若干处逻辑判断，可以重新编译一下

JS 的替换可以用我改好的版本 `https://EndlessCheng.github.io/majsoul/code.js`

**Comment by endlessWar** [comment]
![image](https://user-images.githubusercontent.com/47861644/53617232-49b9a000-3c21-11e9-88c7-1972c9aa815c.png)
![image](https://user-images.githubusercontent.com/47861644/53617241-53430800-3c21-11e9-804f-6bf274ff90f6.png)
用你改好的版本不知道为什么会重定向到这个地址，这个地址是http协议的，会报错

**Comment by EndlessCheng** [comment]
这样啊，那就用 `https://jianyan.me/majsoul/code.js`  这个好了

**Comment by endlessWar** [comment]
新编译的版本输出了我所有的好友信息，开了一局人机，暂时没问题
