### ISSUE TITLE
错误的分析

### ISSUE THREAD

**Issue by Mooos-MoSheng** [EndlessCheng/mahjong-helper#140]
![image](https://user-images.githubusercontent.com/46639923/142557706-d9865c5b-a9d4-4f5e-b9ef-148f81184145.png)

**Comment by EndlessCheng** [comment]
感谢反馈，我有空看看

**Comment by Mooos-MoSheng** [comment]
> 感谢反馈，我有空看看

发现问题了，是PowerShell默认#号以后都是注释。可以替换一下关键字吗。

**Comment by Mooos-MoSheng** [comment]
或者增加一个除了#之外的关键字

**Comment by EndlessCheng** [comment]
可以加上引号，比如 `mahjong-helper "1p # 123p 234s 345m 111z"`

**Comment by Mooos-MoSheng** [comment]
嗯，但是会有些不方便。
我先这么用着吧。
