### ISSUE TITLE
关于役

### ISSUE THREAD

**Issue by sgpsdd** [EndlessCheng/mahjong-helper#142]
为什么碰了个发，手上有一筒时显示无役

**Comment by EndlessCheng** [comment]
牌谱可以发一下吗？

**Comment by sgpsdd** [comment]
> 牌谱可以发一下吗？可以私信发我邮箱 [cheng.endless@gmail.com](mailto:cheng.endless@gmail.com)

如何导出牌谱

**Comment by EndlessCheng** [comment]
> > 牌谱可以发一下吗？可以私信发我邮箱 [cheng.endless@gmail.com](mailto:cheng.endless@gmail.com)
> 
> 如何导出牌谱

点击「牌谱」-「分享」，把链接发给我

**Comment by EndlessCheng** [comment]
明白了，是空听的情况，这里显示的是无役。

我记下来了，感谢您的反馈。
