### ISSUE TITLE
开过助手后雀魂和天凤都无法登陆了

### ISSUE THREAD

**Issue by jianxinnba** [EndlessCheng/mahjong-helper#143]
![QQ截图20211203212531](https://user-images.githubusercontent.com/95483998/144609974-5c38eaec-54df-40dc-8db4-a20437a965e9.png)
开启后雀魂不能登陆了

**Comment by EndlessCheng** [comment]
点进 Header Editor 扩展的`管理`界面，清空原有规则，然后点击`导入和导出`，在下载规则中填入 `https://endlesscheng.gitee.io/public/mahjong-helper.json`，点击右侧的下载按钮，然后点击下方的`保存`。（如果您是海外用户，请在下载规则中填入 `https://mjhelper.github.io/mahjong-helper.json` 以获得更好的加载速度。）

**Comment by jianxinnba** [comment]
多谢 已经解决了
