### ISSUE TITLE
在解析雀魂牌谱时出现内部错误

### ISSUE THREAD

**Issue by Tender-Su** [EndlessCheng/mahjong-helper#146]
![image](https://user-images.githubusercontent.com/37078417/148548368-d5c0612d-68a2-4568-a602-7f9cde70d59b.png)

**Comment by EndlessCheng** [comment]
可以贴一下牌谱链接吗

**Comment by Tender-Su** [comment]
雀魂牌谱: https://game.maj-soul.com/1/?paipu=210305-14e4f4d0-c8b2-430e-a953-27b3251770e3_a110661023

**Comment by fysly** [comment]
> 可以贴一下牌谱链接吗

这个问题好像挺普遍的，一打开其他人的牌谱，开始切第一张牌就会报错 runtime error: index out of range [0] with length 0
但是印象中以前是没问题的，可能是近期雀魂更新后才新出现的问题。另外，观战也是同样的内部错误。

牌谱： https://game.maj-soul.com/1/?paipu=210114-9076dcb4-b76c-427b-a00b-2487b08f177a_a448188510
