### ISSUE TITLE
使用Linux無法開啟助手

### ISSUE THREAD

**Issue by forggy0113** [EndlessCheng/mahjong-helper#149]
目前使用Manjaro 
已經把助手檔案chmod +x 了
還是無法啟動助手
報錯 bash: mahjong-helper-linux: command not found

**Comment by EndlessCheng** [comment]
这个可能是你当前的路径不对？

**Comment by forggy0113** [comment]
我是放在home目錄下的
在home目錄下ls 也有看到檔案
但就無法開啟

**Comment by EndlessCheng** [comment]
试试放到 PATH 环境变量中的某个目录下

**Comment by forggy0113** [comment]
放入PATH路徑之後就能正常啟動了
/home/user/.local/bin

感謝
