### ISSUE TITLE
把本地证书放到代码中，避免某些情况下找不到文件的问题

### ISSUE THREAD

**Issue by EndlessCheng** [EndlessCheng/mahjong-helper#15]

**Comment by EndlessCheng** [comment]
目前生成的程序在命令行是可以打开的，但是直接双击打开可能会提示找不到证书文件

**Comment by toaruI** [comment]
mac用户，命令行是这样的提示：
![screenshot 2019-03-01 at 10 36 05](https://user-images.githubusercontent.com/48120483/53629428-d22e4580-3c0d-11e9-8c95-1b77dd5aa6c4.png)
如果直接双击打开是这样的提示：
![screenshot 2019-03-01 at 10 36 49](https://user-images.githubusercontent.com/48120483/53629466-ec682380-3c0d-11e9-9602-5f90db4bd1d7.png)

**Comment by EndlessCheng** [comment]
@toaruI  命令行执行的时候，当前目录是在程序所在目录下吗？

**Comment by toaruI** [comment]
> @toaruI 命令行执行的时候，当前目录是在程序所在目录下吗？

确实不是的，感谢解答。现在没问题了，显示了我的好友和id
![screenshot 2019-03-01 at 10 58 04](https://user-images.githubusercontent.com/48120483/53630665-e45db300-3c10-11e9-8135-b5d30799d86e.png)

**Comment by EndlessCheng** [comment]
@toaruI  你有用到 Nginx 吗？可能是这个原因
这个程序是可以直接运行的，运行后就开启了 HTTPS Web 服务

**Comment by EndlessCheng** [comment]
@toaruI  我刚才提交了代码，你重新下载编译后就没有文件存在的问题了

**Comment by toaruI** [comment]
> @toaruI 我刚才提交了代码，你重新下载编译后就没有文件不存在的问题了（命令行或直接打开都可以）

问题已解决，感谢
