### ISSUE TITLE
请问助手的启动文件在哪里，如何启动

### ISSUE THREAD

**Issue by fruit141** [EndlessCheng/mahjong-helper#150]
没找到exe的启动文件，麻烦讲一下如何启动助手

**Comment by EndlessCheng** [comment]
按安装步骤安装。

Windows 用户下载 [releases](https://github.com/EndlessCheng/mahjong-helper/releases/latest) 页面下的 [mahjong-helper-v0.2.8-win64-x64.zip](https://github.com/EndlessCheng/mahjong-helper/releases/download/v0.2.8/mahjong-helper-v0.2.8-win64-x64.zip)
