### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by DKNight-9207** [EndlessCheng/mahjong-helper#151]
![image](https://user-images.githubusercontent.com/68389902/159030103-017440ea-cead-4fcd-9bf6-3c934ee4e546.png)
我沒九萬，系統出現打九萬的選項

**Comment by DKNight-9207** [comment]
對了，這局因為有事就中離了
沒能存到牌譜

**Comment by EndlessCheng** [comment]
尚不支持修罗
