### ISSUE TITLE
readme里的这个例子的疑问 

### ISSUE THREAD

**Issue by murphymeng** [EndlessCheng/mahjong-helper#154]
## readme里的这个例子的疑问 

![image](https://user-images.githubusercontent.com/7246104/161743462-6fff064b-e336-45af-b144-994b473b4507.png)

请问如果选择切3饼，接下去假设摸到7索，就听4张6饼和9饼，一共8张牌，为什么这里显示6？

**Comment by EndlessCheng** [comment]
这里是平均听牌，切 3p 后，如果摸到 6p 或者 9p 就只能听 7s 了。
