### ISSUE TITLE
出现了以下问题请问怎么解决

### ISSUE THREAD

**Issue by z878325145** [EndlessCheng/mahjong-helper#155]
![47{1`XB KXP)M0EIPBXT%$2](https://user-images.githubusercontent.com/105547610/168424779-3f0fbe95-0d2d-4e02-a926-15c32e885528.png)

**Comment by EndlessCheng** [comment]
见 #104  ，如仍未解决请在其下回复

**Comment by z878325145** [comment]
请问如何解决
![168424779-3f0fbe95-0d2d-4e02-a926-15c32e885528](https://user-images.githubusercontent.com/105547610/168424971-f8fa0e47-0029-471f-9b76-091052cede27.png)
