### ISSUE TITLE
localhost有问题怎么办

### ISSUE THREAD

**Issue by mshisla** [EndlessCheng/mahjong-helper#158]
<img width="356" alt="98F4ECB1-7CCB-4690-825E-39F6F3BE0CAE" src="https://user-images.githubusercontent.com/104636771/168536484-f90b0e45-9c42-4436-a8e3-7455366607f7.png">

**Comment by mshisla** [comment]
尝试点开localhost：12121，显示localhost拒绝了我们的连接需求

**Comment by mshisla** [comment]
更改IIS后卡在雀魂登录页面，黑屏，进不去了

**Comment by mshisla** [comment]
现在能够进入游戏，但是仍然显示localhost12121

**Comment by EndlessCheng** [comment]
请尝试 #104 的解决方案，如有问题请在 #104 下回复。
