### ISSUE TITLE
关于描述提个小建议

### ISSUE THREAD

**Issue by toaruI** [EndlessCheng/mahjong-helper#16]
可以感觉出来不同颜色分别代表铳的概率以及和了的概率，但是如果没有个简单介绍的话总感觉有点“这玩意很厉害但我意识不到很厉害”的感觉。（还有改良和进张和听牌没有个tag，刚一看有点头晕

包括平均听牌数已经平均改良张数刚一看的话有些头晕（希望可以加个描述，例如 数字后面可以加个“张”， 40.34 [5 改良]  6.95 这种表示猛一看也有点头晕，虽然想一想知道是什么意思）

使用的一些基本原理啥的注释里既然写出来了感觉写到介绍里也无妨。

确实花点功夫的话都能弄懂，不过对用户不太友好233，
不过如果作者juju不希望广泛传播的话那还是保持原样233（要编译让人有点这种感觉x

话说标示危险牌的功能就是程序里红色的牌吗

以及没咋感受到异常切牌的标示功能

刚使用几盘，反馈一下

**Comment by EndlessCheng** [comment]
感谢您的反馈~

>可以感觉出来不同颜色分别代表铳的概率以及和了的概率，但是如果没有个简单介绍的话总感觉有点“这玩意很厉害但我意识不到很厉害”的感觉。（还有改良和进张和听牌没有个tag，刚一看有点头晕
>
>包括平均听牌数已经平均改良张数刚一看的话有些头晕（希望可以加个描述，例如 数字后面可以加个“张”， 40.34 [5 改良] 6.95 这种表示猛一看也有点头晕，虽然想一想知道是什么意思）
>
>使用的一些基本原理啥的注释里既然写出来了感觉写到介绍里也无妨。
>
>确实花点功夫的话都能弄懂，不过对用户不太友好233，
>不过如果作者juju不希望广泛传播的话那还是保持原样233（要编译让人有点这种感觉x

编译的事情呢，近期内会发布一个稳定版本到 Releases 中，大致就是解决掉一些bug。
用户体验上的确有不少可以改进的地方。
对于初次使用的人来说，程序上显示的部分内容没有解释到；
但解释过多界面也有些繁复。
目前的想法是，相关的说明在README中完善（或者程序启动时添加），程序上显示的内容尽量精简。

>话说标示危险牌的功能就是程序里红色的牌吗
>
>以及没咋感受到异常切牌的标示功能

你说的是他家舍牌中的标识吗？目前程序对中张（2378、456）舍牌有颜色上的标记，
围绕舍牌的提醒，目前我在思考有没有可以优化和改进的地方，
如果你对这一块功能有什么建议可以说一说

**Comment by toaruI** [comment]
> 感谢您的反馈~
> 
> > 可以感觉出来不同颜色分别代表铳的概率以及和了的概率，但是如果没有个简单介绍的话总感觉有点“这玩意很厉害但我意识不到很厉害”的感觉。（还有改良和进张和听牌没有个tag，刚一看有点头晕
> > 包括平均听牌数已经平均改良张数刚一看的话有些头晕（希望可以加个描述，例如 数字后面可以加个“张”， 40.34 [5 改良] 6.95 这种表示猛一看也有点头晕，虽然想一想知道是什么意思）
> > 使用的一些基本原理啥的注释里既然写出来了感觉写到介绍里也无妨。
> > 确实花点功夫的话都能弄懂，不过对用户不太友好233，
> > 不过如果作者juju不希望广泛传播的话那还是保持原样233（要编译让人有点这种感觉x
> 
> 编译的事情，近期内会发布一个稳定版本到 Releases 中，大致就是解决掉一些 bug。
> 用户体验上的确有不少可以改进的地方。
> 对于初次使用的人来说，程序上显示的部分内容没有解释到；
> 但解释过多界面也有些繁复。
> 目前的想法是，相关的说明在 README 中完善（或者程序启动时添加），程序上显示的内容尽量精简。
> 
> > 话说标示危险牌的功能就是程序里红色的牌吗
> > 以及没咋感受到异常切牌的标示功能
> 
> 你说的是他家舍牌中的标识吗？目前程序对中张（2378、456）舍牌有颜色上的标记，
> 围绕舍牌的提醒，目前我在思考有没有可以优化和改进的地方，
> 如果你对这一块功能有什么建议可以说一说

舍牌的话看懂了之后知道摸切和危险中张后，感觉已经足够，毕竟读牌理论本身也比较玄学（？本人雀力也比较烂感觉提不出啥好的意见了
