### ISSUE TITLE
雀魂官网更新了新的域名 https://game.maj-soul.net/1/ ，旧版本助手无法使用

### ISSUE THREAD

**Issue by 17521066238** [EndlessCheng/mahjong-helper#161]
请作者大大对助手进行更新

**Comment by EndlessCheng** [comment]
信息反馈。
这是备用站，原来的 https://game.maj-soul.com/1/ 还是正常的。
我后面把这个备用站也加到重定向里面，谢谢。

**Comment by mshisla** [comment]
蹲一个更新（我原网址已经登不进去了）

**Comment by Dickoem** [comment]
**恳请作者大神更新。**
**谢谢~！**

**Comment by EndlessCheng** [comment]
可以手动改下规则列表：
左键单击 Header Editor 扩展图标 - 管理 - 规则列表 - 未分组 - 雀魂-国际中文服 - 右边的编辑
把匹配规则从 `^https://game\.maj\-soul\.com/[0-9]+/[a-zA-Z0-9\.]+/code\.js$` 改成 `^https://game\.maj\-soul\.net/[0-9]+/[a-zA-Z0-9\.]+/code\.js$`
点击保存。

**Comment by yangmiyuaini** [comment]
> 可以手动改下规则列表： 左键单击 Header Editor 扩展图标 - 管理 - 规则列表 - 未分组 - 雀魂-国际中文服 - 右边的编辑 把匹配规则从 `^https://game\.maj\-soul\.com/[0-9]+/[a-zA-Z0-9\.]+/code\.js$` 改成 `^https://game\.maj\-soul\.net/[0-9]+/[a-zA-Z0-9\.]+/code\.js$` 点击保存。

还是不行哦 ，改了net，不用VPN，游戏内所有线路就连不上了

**Comment by Dickoem** [comment]
> > 可以手动改下规则列表： 左键单击 Header Editor 扩展图标 - 管理 - 规则列表 - 未分组 - 雀魂-国际中文服 - 右边的编辑 把匹配规则从 `^https://game\.maj\-soul\.com/[0-9]+/[a-zA-Z0-9\.]+/code\.js$` 改成 `^https://game\.maj\-soul\.net/[0-9]+/[a-zA-Z0-9\.]+/code\.js$` 点击保存。
> 
> 还是不行哦 ，改了net，不用VPN，游戏内所有线路就连不上了

我跟您一样，也是这么弄的，但进不了游戏。

**Comment by mshisla** [comment]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/104636771/173173528-f4f24765-6c2a-4855-88a3-ec9fe3f5ba30.png">
如上图，更改后雀魂线路显示获取失败

**Comment by giu2233** [comment]
大佬更新一下设置

**Comment by EndlessCheng** [comment]
已修复。谢谢各位的反馈。

**Comment by EndlessCheng** [comment]
如有问题，可以在导入和导出中重新拉取 `https://endlesscheng.gitee.io/public/mahjong-helper.json`

**Comment by DongGua-Jun** [comment]
> 已修复。谢谢各位的反馈。

提醒各位，记得 按F12 ——》清空缓存进行应刷新。

另外，大大，修罗之战模式能支持一下不

**Comment by DongGua-Jun** [comment]
> > 已修复。谢谢各位的反馈。
> 
> 提醒各位，记得 按F12 ——》清空缓存进行硬刷新。
> 
> 另外，大大，修罗之战模式能支持一下不

修罗之战，赤羽之战模式，换牌之后，终端不会刷新手牌。
仍然以换牌之前的手牌进行计算
