### ISSUE TITLE
观看牌谱时出现invalid memory address错误

### ISSUE THREAD

**Issue by SeiunSky0131** [EndlessCheng/mahjong-helper#166]
在进入一个牌谱并输出四家信息后，无法读取起手，显示以下错误：
内部错误： runtime error: invalid memory address or nil pointer dereference

**Comment by teble** [comment]
作者的js文件存在一处错误，导致传给后台的json数据无法对应代码结构，作者的文件`code-zh.js`关键词actions.push(h);这里push的应当是Q，自行修改

**Comment by EndlessCheng** [comment]
谢谢反馈

**Comment by EndlessCheng** [comment]
麻烦看一下是否还会有此问题

**Comment by czh18773487659** [comment]
现在变成数据异常：未收到RecordNewRound，摸牌后出现内部错误： runtime error: index out of range [0] with length 0提示

**Comment by teble** [comment]
[code.js.zip](https://github.com/EndlessCheng/mahjong-helper/files/9027063/code.js.zip)
这份是我自己改的最新的js文件，用过了没问题，需要自取（仅限zh版本）

**Comment by EndlessCheng** [comment]
Fixed.
