### ISSUE TITLE
牌桌位置获取错误

### ISSUE THREAD

**Issue by qqshipigo** [EndlessCheng/mahjong-helper#173]
位置错开了，无法正常分析牌。

**Comment by BeiYingxgg** [comment]
同

**Comment by iranzai** [comment]
同

**Comment by EndlessCheng** [comment]
没复现此问题，麻烦提供截图。

**Comment by qqshipigo** [comment]
> 没复现此问题，麻烦提供截图。
![QZ8FOML}B5IS`2%ASQH@ELI](https://user-images.githubusercontent.com/59407780/185548074-13b252a9-04c4-41ab-879e-7576513f3d9d.png)
如下

**Comment by EndlessCheng** [comment]
无法复现此问题，请确保关闭了其它雀魂插件。助手不保证与其它插件完美兼容。

**Comment by xujiawei98** [comment]
同出现牌桌识别错误的问题

**Comment by habayashi** [comment]
同出现此问题，并未安装其他插件。
