### ISSUE TITLE
国服:加载失败

### ISSUE THREAD

**Issue by Agnes4m** [EndlessCheng/mahjong-helper#174]
无法连接国服，已经按照readme，下载了chrome插件，win10 64
![image](https://user-images.githubusercontent.com/70925546/185656138-c53e79b7-842b-4cc9-908a-6ade5373d661.png)
![image](https://user-images.githubusercontent.com/70925546/185655904-01dc7aad-c2fb-42f7-a0fb-841dc55258b8.png)

**Comment by EndlessCheng** [comment]
这个加载失败的图是哪里的

**Comment by Agnes4m** [comment]
releases里，win64

**Comment by EndlessCheng** [comment]
你说的不是我这个项目，我的项目没有这个图。
