### ISSUE TITLE
我装了Issue指向的header editor 也导入了那个url但是还是未响应按f12也没有code-zh.js

### ISSUE THREAD

**Issue by TripleLLLV** [EndlessCheng/mahjong-helper#176]
rt

**Comment by TripleLLLV** [comment]
好了它现在有code-zh.js，但现在网页版无法进入，我清空缓存并硬刷新后有了code-zh.js但是网页黑屏了无法进入

**Comment by EndlessCheng** [comment]
黑屏说明加载速度过慢，安装过程的第二步，国内用户用 https://endlesscheng.gitee.io/public/mahjong-helper.json ，海外用户用  https://mjhelper.github.io/mahjong-helper.json ，可解决大多数加载过慢的问题。

**Comment by TripleLLLV** [comment]
我国内国外的都试了，只要Header editor的那个成功启动它就会黑屏，我把header editor关了后就能正常进入
