### ISSUE TITLE
控制台输出有时会多于25行

### ISSUE THREAD

**Issue by ayssia** [EndlessCheng/mahjong-helper#18]
在windows下会导致上面的输出被挤掉，需要手动翻页。

建议只输出最重要的几种切法以保证不超过25行。

**Comment by EndlessCheng** [comment]
25行有点困难，毕竟还要显示他家何切，安牌
一个方案是加个选项
或者可以修改控制台的字体大小

**Comment by EndlessCheng** [comment]
v0.1.2 发布，在向听倒退没有优势的时候不会打印向听倒退的内容了

**Comment by EndlessCheng** [comment]
现在改成了单行模式，大多数情况都在25行内
