### ISSUE TITLE
最新的0.1.2版编译好像有点问题

### ISSUE THREAD

**Issue by toaruI** [EndlessCheng/mahjong-helper#21]
虽然直接可以下载了，不过从源码编译的时候好像出现了这样的提示

cli.go:8:2: cannot find package "EndlessCheng/mahjong-helper/util" in any of:
	/Users/liujinmin/go/src/mahjong-helper-master/vendor/EndlessCheng/mahjong-helper/util (vendor tree)
	/usr/local/Cellar/go/1.12/libexec/src/EndlessCheng/mahjong-helper/util (from $GOROOT)
	/Users/liujinmin/go/src/EndlessCheng/mahjong-helper/util (from $GOPATH)
tsf-484-wpa-7-023:mahjong-helper-master liujinmin$

**Comment by EndlessCheng** [comment]
这个是 go 语言的坑，编译的话项目必须放在 `$GOPATH/src/` 下，比如我的项目目录是 `C:\Users\Endless\go\src\EndlessCheng\mahjong-helper`

加入了 util 包之后没考虑到这个问题，我看看怎么调整一下

**Comment by EndlessCheng** [comment]
更新了代码和 README 说明
