### ISSUE TITLE
天凤进入网页http://tenhou.net/3/并登陆进入游戏后客户端无反应

### ISSUE THREAD

**Issue by Moeblack** [EndlessCheng/mahjong-helper#23]
天凤进入网页http://tenhou.net/3/并登陆进入游戏后客户端无反应
![可以石油_1](https://user-images.githubusercontent.com/28835093/54750558-08f6ea80-4c13-11e9-84d2-de6873cedc60.png)

**Comment by EndlessCheng** [comment]
天凤不会对登录进行处理，可以开一局游戏看看

**Comment by Moeblack** [comment]
依旧没有反应
![可以石油_2](https://user-images.githubusercontent.com/28835093/54789802-b77c4900-4c6e-11e9-8f5a-9873beb1c39e.png)

**Comment by EndlessCheng** [comment]
那就有点奇怪了

请上传一下程序所在目录下的 `gamedata.log` 文件

**Comment by EndlessCheng** [comment]
还有可能是你没有把天凤的 js 重定向

可以重新载入下 `https://jianyan.me/js/mahjong-helper.json` 到 Header Editor 中试试

**Comment by Moeblack** [comment]
[gamedata.log](https://github.com/EndlessCheng/mahjong-helper/files/2995925/gamedata.log)
已经重载入一次 依旧无反应

**Comment by EndlessCheng** [comment]
从日志上来看，程序在运行雀魂时正常收到消息了，但是在运行天凤的时候没有收到消息

原因可能是 Header Editor 没有正确处理天凤的 js 重定向

你能提供这两份截图吗？

1. 在天凤页面打开开发者工具(F12)，选择网络(Network)，然后刷新天凤页面，查看 JS 内容是否有 code.js

2. 查看 Header Editor 是否载入正确，即规则列表中是否有重定向至 https://jianyan.me/tenhou/code.js 的规则

**Comment by EndlessCheng** [comment]
我找到问题了，Chrome 浏览器下的 Header Editor 插件没有正确识别跳转时的匹配规则，我修改了https://jianyan.me/js/mahjong-helper.json，你重新在 Header Editor 中加载一下就行了（或者清空原有的规则，然后再加载）

**Comment by Moeblack** [comment]
谢谢 问题已解决
