### ISSUE TITLE
游戏协议变动

### ISSUE THREAD

**Issue by lxy7065809** [EndlessCheng/mahjong-helper#24]
雀魂28日开服后code.js文件有所更新，使用当前的0.1.4版本会出现游戏中许多变量显示为undefined，友人场页面打开报错等问题。

**Comment by EndlessCheng** [comment]
收到，会尽快解决

**Comment by EndlessCheng** [comment]
修复完成，刷新网页就行了

如果还不行的化请重新载入一下规则到 Header Editor

**Comment by toaruI** [comment]
好像还是有问题，感觉是https://jianyan.me/majsoul/code.js里面的code.js有些问题
