### ISSUE TITLE
有的牌识别不出来

### ISSUE THREAD

**Issue by MCsentic** [EndlessCheng/mahjong-helper#25]
![%8_(5MXHZ7 WVJ@IEQU$T4Y](https://user-images.githubusercontent.com/28777951/55287174-26c50c00-53d8-11e9-8a02-8e0a80803f3a.png)

如图所示，别家打出来的牌有的时候会识别不出来
还没注意到发生的时机，不过好像某一家的牌被鸣走之后下一次切牌就大概率识别不出来

**Comment by EndlessCheng** [comment]
模切的牌显示为 --

**Comment by EndlessCheng** [comment]
新版的改成了暗色字体，可以消除这个误会了
