### ISSUE TITLE
修改js后会长时间卡在加载页面的36%进入游戏之后无法玩耍

### ISSUE THREAD

**Issue by endlessWar** [EndlessCheng/mahjong-helper#26]
如题，
![image](https://user-images.githubusercontent.com/47861644/55451982-f368c400-5607-11e9-9983-65c1d61ffbc7.png)

**Comment by endlessWar** [comment]
此次更新后出现该问题

**Comment by EndlessCheng** [comment]
感谢反馈，我更新了JS，请刷新网页试试

**Comment by kfkots** [comment]
此次更新后又出现了这个问题
