### ISSUE TITLE
感谢作者~

### ISSUE THREAD

**Issue by xccwhy** [EndlessCheng/mahjong-helper#28]
用了两天还不错，特地注册个帐号前来感谢作者~有几点小问题反馈下。
1.客户端天风没反应，另外一个正常。
2.分析界面花花绿绿看得时间长了不太舒服，如果是按照优先级来制定颜色的话，那可以理解，如果没有优先级的话，可否对颜色上稍微做下调整呢。
3.请问下在界面中，优先级是按照顺序排列的还是颜色呢。

**Comment by xccwhy** [comment]
客户端挺好用的~真诚感谢

**Comment by EndlessCheng** [comment]
感谢反馈~

> 1.客户端天风没反应，另外一个正常。

天凤要进入到对战界面才会有信息提醒，如果还没有请提供浏览器名称、版本。

这么说的话登录天凤时可以加个提醒，这样就和雀魂的提醒是统一的。

> 2.分析界面花花绿绿看得时间长了不太舒服，如果是按照优先级来制定颜色的话，那可以理解，如果没有优先级的话，可否对颜色上稍微做下调整呢。

制定颜色是个好想法。对于此我打算加个设置选项，比如让用户自己选择各种颜色（切换配色方案），或者取消高亮显示等（摸切、安牌、何切分析可以单独设置）。

因为命令行界面能用的颜色过于少，相比网页在色彩这一块有很大弊端，这是我打算开发网页版本的原因之一（见 [制作一个类似 tenhou.net/2 一样的前端？](https://github.com/EndlessCheng/mahjong-helper/issues/27)）。

> 3.请问下在界面中，优先级是按照顺序排列的还是颜色呢。

按照顺序，颜色是次级参考

**Comment by xccwhy** [comment]
1.摸切可以考虑录像中默认的“灰色”。
2.安牌可以参考“红绿灯”形式，对于安牌这块上，不知道有没有关于“筋”的算法，可能这块要麻烦作者琢磨一下了。
3.何切分析现在这个现在做的无可挑剔，关于颜色这块，默认是现在的颜色样式其实也可以接受，关于“颜色自定义”这个我代表不了大众，没有发言权，这还要靠大家后续的反馈了。

**Comment by EndlessCheng** [comment]
> 1.摸切可以考虑录像中默认的“灰色”。

不久前我更新了一个版本，把摸切牌用灰色表示了（旧版本是用的「--」），可以更新到最新版试试

> 2.安牌可以参考“红绿灯”形式，对于安牌这块上，不知道有没有关于“筋”的算法，可能这块要麻烦作者琢磨一下了。

安牌是综合考虑巡目、筋牌和 No Chance 壁牌，然后按照铳率排序的。

目前安牌是「蓝-黄-红」的样式，你说的红绿灯是指颜色上的「绿-黄-红」吗？还是指排列方式？

**Comment by christensennn** [comment]
关于颜色我也想说句 深蓝色字体在黑色窗口里实在不太看得清。。建议浅色调

**Comment by EndlessCheng** [comment]
@christensennn  这个建议可以，之前我一直使用的 GoLand 中的终端， Windows 自带的很少使用。

最近在优化颜色这部分内容，包括 Windows 终端中的蓝色过于暗淡的问题，会在下个版本中修复

**Comment by christensennn** [comment]
> @christensennn 这个建议可以，之前我一直使用的 GoLand 中的终端， Windows 自带的很少使用。
> 
> 最近在优化颜色这部分内容，包括 Windows 终端中的某些红黄蓝过于暗淡的问题，会在下个版本中修复

谢谢

**Comment by EndlessCheng** [comment]
@xccwhy  @christensennn  发布了一个小版本，请前往 https://github.com/EndlessCheng/mahjong-helper/releases 下载

如果在使用中有什么建议、想法可以继续反馈~
