### ISSUE TITLE
关于何切顺序一些不太关键的问题

### ISSUE THREAD

**Issue by christensennn** [EndlessCheng/mahjong-helper#31]
关于字牌何切的问题 既然可以判断自风 是否能将其加入考量 比如自风为西 手上一张西风一张南风 牌河指示牌不出现相关牌的时候 切西风的顺序在南风之后而不是随机（手牌从左往右？）
关于七对子的问题 有时候4对子的时候似乎会显示两向听以及相关何切  实际体验下7对子两向听离听牌可能很远很远 虽然这个时候应该也有一般型三向听的选项在后面 能否对 七对子/国士无双这种特殊牌型的向听建议前进行标注？
当然这两个问题都并不太影响实际体验 玩家做这些个基本判断的能力还是有的 只不过能改进就更好了
关于役的判断的问题 我看到之前的issue已经有提到了就不重复了
（顺带想问下 听牌型好坏决定是否倒退or改良 如果单纯看加权后的听牌数划线的话 5.0张上下比较合理？）
谢谢！

**Comment by EndlessCheng** [comment]
> 关于字牌何切的问题 既然可以判断自风 是否能将其加入考量 比如自风为西 手上一张西风一张南风 牌河指示牌不出现相关牌的时候 切西风的顺序在南风之后而不是随机（手牌从左往右？）

可以，算是微小的调整

不过做平和的话还是留客风比较好，不一定是役牌优先的

> 关于七对子的问题 有时候4对子的时候似乎会显示两向听以及相关何切 实际体验下7对子两向听离听牌可能很远很远 虽然这个时候应该也有一般型三向听的选项在后面 能否对 七对子/国士无双这种特殊牌型的向听建议前进行标注？

我正在考虑做标注役种的功能，鉴于七对子特征十分明显，可以直接加到何切分析中

国士的话程序是不考虑的，毕竟如果要凹国士话无脑凹就行了（笑）

> 顺带想问下 听牌型好坏决定是否倒退or改良 如果单纯看加权后的听牌数划线的话 5.0张上下比较合理？

这个建议是出于什么考虑呢？

有时候出于提高打点的目的，即便是好型听牌也会有向听倒退的考虑（比如 AL 中的做牌）

目前程序是判断倒退回一向听后，根据进张数量是否充足来决定是否显示一向听分析

**Comment by christensennn** [comment]
> > 顺带想问下 听牌型好坏决定是否倒退or改良 如果单纯看加权后的听牌数划线的话 5.0张上下比较合理？
> 
> 这个建议是出于什么考虑呢？
> 
> 有时候出于提高打点的目的，即便是好型听牌也会有向听倒退的考虑（比如 AL 中的做牌）
> 
> 目前程序是判断倒退回一向听后，根据进张数量是否充足来决定是否显示一向听分析

按照你的意思的话显示一向听分析就是进张数不够了那我觉得从程序上就ok了 从你的readme描述和我的实际经验来讲我感觉是5张左右就可以听了而3张太少能改良就改良（不考虑打点高低） 提问只是单纯看看我的判断对不对

**Comment by EndlessCheng** [comment]
嗯，其实大多情况都是好型即立的，愚型没啥改良也会考虑即立

感谢反馈~上面说的建议我都会采纳

后续若有使用上的不便之处还请多多吐槽~

**Comment by EndlessCheng** [comment]
修复于  [v0.2.2](https://github.com/EndlessCheng/mahjong-helper/releases/tag/v0.2.2)

**Comment by EndlessCheng** [comment]
> 关于字牌何切的问题 既然可以判断自风 是否能将其加入考量 比如自风为西 手上一张西风一张南风 牌河指示牌不出现相关牌的时候 切西风的顺序在南风之后而不是随机（手牌从左往右？）

修复于 [v0.2.4](https://github.com/EndlessCheng/mahjong-helper/releases/tag/v0.2.4)
