### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by xccwhy** [EndlessCheng/mahjong-helper#32]
1.可否增加关于“筋”的判断选项
2.手里已听牌假设13m，而2m已经给杠走了，依然不提示让你换听……

**Comment by EndlessCheng** [comment]
> 可否增加关于“筋”的判断选项

能描述详细一点吗，是指的防守时的判断吗？

> 手里已听牌假设13m，而2m已经给杠走了，依然不提示让你换听……

目前的提示是「已听牌，0 进张」，你是指在这种情况下有额外提示吗？
