### ISSUE TITLE
有关铳牌展示的一些小看法

### ISSUE THREAD

**Issue by FreshyLuLu** [EndlessCheng/mahjong-helper#33]
有其他两家或者三家疑似听牌的时候，要看的安牌太多了，体验很不好。
建议就是在何切的后面加上切这个牌更有可能放铳给哪一家的提示。这样的话在自己想要胡牌的情况下，根据其他家的副露情况来决定是否要打，这样子会好一些吧？
（举个例子，比如上家副露了很多宝牌，而对家的牌型分值应该不高，在决定何切的时候如果还要对比这个程序里面两家的安牌以及自己的何切的话，体验真的不太好；所以不如就在何切的后面或者用其他方式来让用户直观感受到风险最低而自己听牌权重最多的选项？）

**Comment by EndlessCheng** [comment]
感谢你的反馈。

防守多家时，程序给出的信息确实如你所说，在短时间内综合判断一张牌的危险度是有些难度的。

我的想法是估计各家的打点、听牌率等算出打出某张牌的平均危险度，然后排序显示，排序靠前的牌是相对安全的

**Comment by christensennn** [comment]
如果估计各家打点 程序可以辨识dora的话 将宝牌理论考虑进安牌顺序算是个改进不？（今天刚点了个炮 就是含dora面子的两面 有感而发）

**Comment by EndlessCheng** [comment]
@christensennn  

感谢反馈。我查了一下数据，切 dora 的铳率没高到多少，但是失点期望值要比非 dora 高约 40%，比如说无筋 dora 2 比无筋非 dora 5 失点更高。基于这一点可以把 dora 的危险度提高一档。

dora 周边、dora 筋的危险度略有提升，可以考虑调整下相关铳率。

**Comment by christensennn** [comment]
> @christensennn
> 
> 感谢反馈。我查了一下数据，切 dora 的铳率没高到多少，但是失点期望值要比非 dora 高约 40%，比如说dora 1 比非 dora 1 失点高约 40%，无筋 dora 2 和无筋非 dora 5 失点差不多。基于这一点可以把 dora 的危险度提高一档。
> 
> dora 周边、dora 筋的危险度略有提升，可以考虑调整下相关铳率。

我想表达的就是dora周边的危险率有所提升 尤其是dora越靠近19的时候

**Comment by EndlessCheng** [comment]
@FreshyLuLu  @christensennn  新版本已发布，请前往 https://github.com/EndlessCheng/mahjong-helper/releases/latest 下载

**Comment by EndlessCheng** [comment]
调整防守时的舍牌文字颜色：[v0.2.2](https://github.com/EndlessCheng/mahjong-helper/releases/tag/v0.2.2)
