### ISSUE TITLE
请求增加对日服的支持

### ISSUE THREAD

**Issue by sibalaxiii** [EndlessCheng/mahjong-helper#35]

**Comment by sibalaxiii** [comment]
够快的

**Comment by Arisix** [comment]
將Header Editor的majsoul規則clone一筆出來比對規則改為
`^https://game\.mahjongsoul\.com/[a-zA-Z0-9\.]+/code\.js$`
目前暫時可以這樣使用

**Comment by xccwhy** [comment]
同求+1

**Comment by EndlessCheng** [comment]
@sibalaxiii  @Arisix  @xccwhy 昨晚就已经支持日服和国际服了哦~重新导入 https://jianyan.me/js/mahjong-helper.json 就可以了
