### ISSUE TITLE
火狐怎么设置允许本地证书通过浏览器？

### ISSUE THREAD

**Issue by jasenwdh** [EndlessCheng/mahjong-helper#37]
我尝试了一下，chrome可以正常使用这个插件，但是Firefox就不行，我觉得问题出在这个证书上。火狐打开了about:config我也没找到相应的设置。

**Comment by EndlessCheng** [comment]
十分抱歉，现在还不支持火狐，我暂时还没找到支持火狐的方式，可能以后跟换成网页插件的形式能解决不同浏览器的问题
