### ISSUE TITLE
请教下使用上的问题

### ISSUE THREAD

**Issue by xccwhy** [EndlessCheng/mahjong-helper#38]
关于 [10无筋] [7无筋]
1.这里的10指的的是什么呢
2.这个7是所有花色的吗，如果不是的话，是不是把花色漏了……
感谢答疑~

**Comment by EndlessCheng** [comment]
指的是无筋数量

剩余无筋数量越少，无筋牌就越危险

但是当剩余数很小的时候(<=2)，该家更有可能是愚型听牌或振听

**Comment by EndlessCheng** [comment]
更新了 README
