### ISSUE TITLE
实际应用中的疑问

### ISSUE THREAD

**Issue by sibalaxiii** [EndlessCheng/mahjong-helper#39]
![image](https://user-images.githubusercontent.com/49758370/57016025-72264080-6c4a-11e9-91a0-61c66c02e99f.png)
游戏中情急之下图没有截全不好意思 这个第二巡切6s进张综合分只有20为何会排在北和发前面 是单纯因为两向听后的进张数多还是别的？（事实上前一回合切6s的选项排到第一 6s为本场指示牌）按照这样的排序切牌是否真的最大化了牌效？谢谢
https://majsoul.union-game.com/0/?paipu=190501-9752d5c3-5a94-48ad-8291-da8a089b62a9_a90654534
本场牌谱 截图的情形发生在南四局前两巡。

**Comment by EndlessCheng** [comment]
感谢反馈。

6s 排在前面是因为目前程序把手牌改良的优先级排在进张和向听前进进张之后。

看了下牌谱，感觉对这种进张很差的形状，把改良排在前面会好些。（<-- 下次版本发布会调整下何切排序）

顺带一提，这里 AL 作为大 TOP 打 6s 也没问题，保留字牌、瞄准七对，有人鸣牌或立直时弃和就行。把字牌全部打出是不推荐的。如果是平场，这样的三对子手牌推荐打 1p 拆掉一个对子。

**Comment by EndlessCheng** [comment]
修复于  [v0.2.2](https://github.com/EndlessCheng/mahjong-helper/releases/tag/v0.2.2)
