### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by sibalaxiii** [EndlessCheng/mahjong-helper#41]
![image](https://user-images.githubusercontent.com/49758370/57084095-41b6d300-6d2c-11e9-9d04-00fb860db555.png)
![image](https://user-images.githubusercontent.com/49758370/57084237-88a4c880-6d2c-11e9-8234-8ed3cce540ad.png)

哦好像并不是错误。。
这个7067指的是根据听牌后不同的胡牌情况点数不同的平均得点吗？

**Comment by EndlessCheng** [comment]
> 这个7067指的是根据听牌后不同的胡牌情况点数不同的平均得点吗？
是的~

**Comment by sibalaxiii** [comment]
还有个小问题 我根据（8000x4+5200x2）/6得出了7067这个结果 我想知道关于边张和中张的胡率加权是34567都算中张还是37和456分开 如果是后者的话 那么计算胡率的时候是不是也应该加权得出一个略大于7067的值（胡牌时 胡7m的概率还要略高于4/6）？谢谢

**Comment by EndlessCheng** [comment]
> @sibalaxiii 还有个小问题 我根据（8000x4+5200x2）/6得出了7067这个结果 我想知道关于边张和中张的胡率加权是34567都算中张还是37和456分开 如果是后者的话 那么计算胡率的时候是不是也应该加权得出一个略大于7067的值（胡牌时 胡7m的概率还要略高于4/6）？谢谢

你说的对，我漏算了和率。感谢指出~下个版本会改进此问题。

**Comment by EndlessCheng** [comment]
这里还有个 bug，5s dora 切掉的话低目应该是 2600，我在算的时候没有考虑切掉的牌是 dora 的情况
