### ISSUE TITLE
牌谱分析功能

### ISSUE THREAD

**Issue by chaserhkj** [EndlessCheng/mahjong-helper#43]
我刚刚在[这个项目](https://github.com/chaserhkj/majsoul-record-dump)里完成了雀魂的RPC框架和雀魂牌谱的批量下载脚本。

现在我想做一个高级牌谱分析器，主要可能有两部分：

一部分是比雀魂更细致的统计数据分析，分场别和场景统计不同的具体统计数据，比如立直后点炮率、良型立直率与愚型立直率之类的

另一部分更接近一个自动复盘器，相当于我希望能用 mahjong-helper 的功能重新评估牌谱里我每一手的切牌合理性，然后统计出牌效率精确度和防守精确度之类的统计数据

一部分这些功能已经有一些别的项目做过了（比如为天凤写的[这个](https://euophrys.itch.io/mahjong-efficiency-trainer))，但是大多做的还不够细致和深入，并且支持的麻将对战平台和牌谱格式也各有不同，我另外也打算写一个交换性比较强的牌谱格式和相应的转换工具来把各个平台的牌谱都统一到这个框架下分析 (格式起了个[草稿](https://github.com/chaserhkj/mahjong-format)) 但是现在打算先从雀魂下手

于是我目前希望能够尽量复用这个项目中的既有代码，这样数据结构和代码框架都不用重新设计并且也可以直接使用这个项目的牌效率推荐算法和防守推荐算法。mahjong-helper 有任何打算支持这一类功能的计划么？ 我可以开个Branch给 mahjong-helper 直接做牌谱分析功能，或者直接把 `utils/` 下面的内容当成库另开项目，哪一种方式你觉得比较合适呢？

**Comment by EndlessCheng** [comment]
感谢你对本项目的关注。

> 我希望能用 mahjong-helper 的功能重新评估牌谱里我每一手的切牌合理性，然后统计出牌效率精确度和防守精确度之类的统计数据
> 一部分这些功能已经有一些别的项目做过了（比如为天凤写的这个)，但是大多做的还不够细致和深入

追求细致和深入的话，本项目虽然在牌效率上多了一些如改良之类的考虑，但实际上，更加精确的算法是基于机器学习统计天凤凤凰桌的牌谱，对每个具体场况给出「顺位最佳」的打法，具体见[水上直纪的论文](https://github.com/EndlessCheng/mahjong-helper/files/3145480/AI.%2B.zip)。与之相比，本项目的相关算法是十分简陋的，个人认为用这去统计牌效和防守精确度不是一个合适的选择。

> 一部分是比雀魂更细致的统计数据分析，分场别和场景统计不同的具体统计数据，比如立直后点炮率、良型立直率与愚型立直率之类的

这个想法很不错，与天凤相比雀魂的统计数据有些简陋，我们可以详细讨论下这部分内容。

我的想法是在用户登录后，获取用户的牌谱，转换牌谱成标准格式，然后解析出像天凤那些良型立直率、追立率等数据，生成一个分析报告（可能是 HTML 文件，或者是一个网址）。

这个分析报告除了上面这些数据外，还可以告诉用户自己牌风是什么样的（门清立直型，副露进攻型，副露防守型等等），和雀魂的魂天/天凤的天凤位哪位风格最接近等等信息。

对此你怎么看？如果你想为本项目贡献代码的话，欢迎 fork。

**Comment by chaserhkj** [comment]
关于自动复盘，我把这个想法和统计数据放在一起的一大原因是在于从代码框架的角度上来讲这两者有很大的相似性：因为牌谱文件可以看作是一个由对局中各种事件（对局开始，摸牌，出牌，吃碰杠）组成的流，统计某些具体数据的统计器和这个自动复盘其实都可以抽象成在这个流上面的一个带内部状态的遍历器。设计相似性让我觉得可以把这两个东西做成一个框架。至于具体的牌效统计，的确从这几篇论文的角度出发可能mahjong-helper的算法简陋了许多，但是我觉得mahjong-helper的算法和数据结构可能是一个不错的出发点，我可能想从这个出发点出发做

至于统计数据分析的问题，生成分析报告是一个不错的点子，问题在于雀魂的牌谱格式也是protobuf的，而且数据量其实不小，对于对局数目比较大的玩家就更多了。我觉得在mahjong-helper的在线自动模式里实时下载和分析可能不太合适，可能用另外的工具来下载和转换牌谱（其实我[这个项目](https://github.com/chaserhkj/PyMajSoul/)已经完成一部分这个功能了），然后再用一个离线的框架来分析牌谱生成报告比较好；当然，如果离线的分析框架写好了再整合进mahjong-helper成为一个功能也是一种可能性

所以我觉得我可以先开一个离线分析的框架，可能会用到 `mahjong-helper/utils` 的数据结构和一些算法，然后在这个基础上做水上直纪的算法以及统计数据分析等。等框架功能齐全了之后再讨论和mahjong-helper整合的可能性

**Comment by EndlessCheng** [comment]
v0.2.5 添加对雀魂牌谱的支持
