### ISSUE TITLE
关于食替的问题。

### ISSUE THREAD

**Issue by FreshyLuLu** [EndlessCheng/mahjong-helper#44]
吃牌之后的食替牌（吃换）牌没有考虑到，虽然平时很容易看出来这个问题，但是还是建议做一下这个功能。

**Comment by FreshyLuLu** [comment]
你好，我指的是吃了上家的牌后破坏已有面子的情况。
如图所示
![_5Y6$)$8J$ VB4C}YJPF%5I](https://user-images.githubusercontent.com/45840777/57358790-c4b2b000-71a8-11e9-932a-b6e8ca07ac43.png)
已有456S的情况下，如果吃进了上家的3S，那么6S就不允许舍出了
![FI%6T2ZOD6B7M{$NJY13(PN](https://user-images.githubusercontent.com/45840777/57358859-e90e8c80-71a8-11e9-9da7-fb5d1cfbe907.png)
但是在程序中没有考虑到
![7VL0X{ X)X6EA1I_FB WVSD](https://user-images.githubusercontent.com/45840777/57358912-04799780-71a9-11e9-8fda-1bf8ab1959bb.png)

**Comment by EndlessCheng** [comment]
感谢反馈。能否提供下使用的版本号和此时的完整手牌？
