### ISSUE TITLE
一个小问题。

### ISSUE THREAD

**Issue by Quattuorlift** [EndlessCheng/mahjong-helper#46]
如果可以根据牌河判断安全牌，那么同理是不是也可以简单地判断对手大概率会切出什么牌，从而在听牌二择的时候更科学地得出不同听形的胡牌概率呢？

**Comment by EndlessCheng** [comment]
好建议。

这个可以算读山的一种，具体到对和率的影响我还需要去研究下相关数据。

**Comment by Quattuorlift** [comment]
好的，加油~
