### ISSUE TITLE
火狐浏览器无法使用插件么？

### ISSUE THREAD

**Issue by haidaopaqis** [EndlessCheng/mahjong-helper#47]
启动软件以后报错echo: http2: server: error reading preface from client [::1]:61348: remote error: tls: bad certificate类似这种，浏览器插件已安装，证书也设置允许

**Comment by EndlessCheng** [comment]
不好意思，由于技术问题暂不支持火狐。
参见 https://github.com/EndlessCheng/mahjong-helper/issues/37
