### ISSUE TITLE
能否增加对32位系统的支持

### ISSUE THREAD

**Issue by Aweeeee** [EndlessCheng/mahjong-helper#49]
如题，Release界面内的程序只有64位系统能打开，希望能加入对32位系统的支持，谢谢！

**Comment by EndlessCheng** [comment]
[mahjong-helper32.zip](https://github.com/EndlessCheng/mahjong-helper/files/3177200/mahjong-helper32.zip)

请试用一下

若下载慢请加群 375865038

**Comment by Aweeeee** [comment]
好的，谢谢
