### ISSUE TITLE
天鳳/雀魂顯示異常 【0.2.5】

### ISSUE THREAD

**Issue by ygyuuffut** [EndlessCheng/mahjong-helper#52]
這個助手在一般情況下是相當好的分析工具，但是在某些情況下就非常頭大。這個助手會在天鳳上面報錯，然後就不顯示了。在雀魂上，這個助手沒有辦法很好的響應牌譜變化（然後黑屏停止工作）。希望這個問題能夠早日修復，繼續努力！

**Comment by EndlessCheng** [comment]
能提供一些截图吗

**Comment by ygyuuffut** [comment]
![error](https://user-images.githubusercontent.com/18429839/58847781-2c4a0700-8652-11e9-87f0-6463c6919fca.PNG)
天鳳報錯（上圖）

**Comment by EndlessCheng** [comment]
在助手所在目录下有一个 gamedata.log 文件，请把这个文件上传发我看看

**Comment by ygyuuffut** [comment]
好的
[gamedata.log](https://github.com/EndlessCheng/mahjong-helper/files/3250301/gamedata.log)

**Comment by EndlessCheng** [comment]
天凤的问题是我在 v0.2.5 版本引入的 bug，解析天凤数据会偶现问题（雀魂不受影响）。

我会尽快修复此问题，你可以先暂时用 [v0.2.4](https://github.com/EndlessCheng/mahjong-helper/releases/tag/v0.2.4)  版本。

雀魂的黑屏问题我怀疑是你误点到了终端的空白处导致终端卡住，此时可以按下回车键使终端恢复正常。

**Comment by EndlessCheng** [comment]
修复于 [v0.2.5a](https://github.com/EndlessCheng/mahjong-helper/releases/tag/v0.2.5a)
