### ISSUE TITLE
牌谱分析 TODO

### ISSUE THREAD

**Issue by EndlessCheng** [EndlessCheng/mahjong-helper#53]
- [x] 支持解析分享的牌谱
- [x] 支持切换主视角
- [x] 支持观战

**Comment by fysly** [comment]
目前的牌谱分析不支持分享，另外有个小问题：某一局最后一巡打不好，想让软件分析一下，但一到最后一巡直接就结束跳到下一局了，而无法给出分析。另外请问是否有可能增加对 [雀魂Plus](https://github.com/MajsoulPlus/majsoul-plus) 的支持？

**Comment by EndlessCheng** [comment]
@fysly  

> 一到最后一巡直接就结束跳到下一局了

我用我自己的牌谱测试，没发现这个问题，只有当最后一张牌打完且出现结算界面后才会跳到下一局。你用的是否为最新版本？如果还有这个问题，和助手文件同一目录下有一个 log 文件夹，可以把最新的 .log 文件上传一下，我看看是什么原因。

雀魂Plus 我看了一下，你可以找一下 code.js 放到哪个目录了，用 https://jianyan.me/majsoul/code-v0.1.4.js 替换就行了

**Comment by fysly** [comment]
重新试了一下没问题了，最后一张牌也还是有分析的。
雀魂Plus我刚才照你说的替换了一下，终端输出：
echo: http2: server: error reading preface from client [::1]:61878: read tcp [::1]:12121->[::1]:61878: read: connection reset by peer

**Comment by EndlessCheng** [comment]
@fysly 出现这个问题应该是需要通过本地证书的方式，也就是我在 README 中写的 `chrome://flags/#allow-insecure-localhost`，不知道雀魂Plus支不支持

**Comment by fysly** [comment]
这大概是不行了，因为没有地址栏找不到打开这个地址的途径，虽然雀魂Plus也有开发者工具的选项，打开后可以看出是和Chrome的一样，应该是Chromium封装的。

**Comment by EndlessCheng** [comment]
@fysly 应该是有方法的，待我找一找

**Comment by EndlessCheng** [comment]
@fysly  我下了一个新的雀魂Plus（文件名是 `Majsoul_Plus-win32-x64-1_11_2.zip`），登录游戏后会生成 `resources\app\static\0\` 目录，在此目录下找到最新的版本对应的文件夹，替换掉里面的 `code.js` 文件就行了。重新登录后，可以看牌谱、对战等。

我没有复现出类似 `echo: http2: server: error reading preface from client [::1]:61878: read tcp [::1]:12121->[::1]:61878: read: connection reset by peer` 这样的信息，能描述下这个错误是在什么情况下报的吗？

**Comment by fysly** [comment]
我使用的是「雀魂Plus v1.12.0-beta.4」Mac版，按照你昨天说的，替换了 `/Application/Majsoul Plus.app/Contents/Resources/app/static/0/v0.5.114.w` 文件夹下的 code.js 文件，然后终端打开程序，启动雀魂plus进入游戏，加载进入主界面时，终端就输出了以下内容，两行。
`echo: http2: server: error reading preface from client [::1]:50976: read tcp [::1]:12121->[::1]:50976: read: connection reset by peer
echo: http2: server: error reading preface from client [::1]:50977: read tcp [::1]:12121->[::1]:50977: read: connection reset by peer`

**Comment by fysly** [comment]
另外如果继续打开牌谱选择页面，点击查看牌谱，也都会输出类似的内容。

> echo: http2: server: error reading preface from client [::1]:51412: read tcp [::1]:12121->[::1]:51412: read: connection reset by peer
> echo: http2: server: error reading preface from client [::1]:51419: read tcp [::1]:12121->[::1]:51419: read: connection reset by peer
> echo: http2: server: error reading preface from client [::1]:51441: read tcp [::1]:12121->[::1]:51441: read: connection reset by peer

**Comment by EndlessCheng** [comment]
@fysly  我看那个版本的更新历史上写着

> 雀魂 Plus 访问远程服务器的安全性被提高了，现在不再会信任所有 https 证书

应该是这个版本不支持助手内置的 localhost 证书导致。

可以使用之前的版本试试。

**Comment by fysly** [comment]
确实如此！换到老版本就没问题了。

**Comment by EndlessCheng** [comment]
完成于 v0.2.6

**Comment by EndlessCheng** [comment]
更新：目前的雀魂 plus 已经支持 mahjong-helper，见 https://github.com/MajsoulPlus/majsoul-plus/pull/86

**Comment by TianYaDY** [comment]
大佬！可以稍微说下怎么和雀魂plus连用吗？雀魂plus没法安装谷歌的那些插件拓展，所以软件没有办法获取数据。

**Comment by EndlessCheng** [comment]
> 大佬！可以稍微说下怎么和雀魂plus连用吗？雀魂plus没法安装谷歌的那些插件拓展，所以软件没有办法获取数据。

@TianYaDY  搜索雀魂 plus 文件夹下的 code.js 文件，然后下载 https://endlesscheng.gitee.io/public/js/majsoul/code-zh.js 把文件名改成 code.js 替换之。

不需要安装任何插件。

**Comment by TianYaDY** [comment]
> > 大佬！可以稍微说下怎么和雀魂plus连用吗？雀魂plus没法安装谷歌的那些插件拓展，所以软件没有办法获取数据。
> 
> @TianYaDY 搜索雀魂 plus 文件夹下的 code.js 文件，然后下载 https://endlesscheng.gitee.io/public/js/majsoul/code-zh.js 把文件名改成 code.js 替换之。
> 
> 不需要安装任何插件。

多谢！另外，我似乎在之前某个JS文件里面看到了乳包内容（手动滑稽）。

**Comment by EndlessCheng** [comment]
> > > 大佬！可以稍微说下怎么和雀魂plus连用吗？雀魂plus没法安装谷歌的那些插件拓展，所以软件没有办法获取数据。
> > 
> > 
> > @TianYaDY 搜索雀魂 plus 文件夹下的 code.js 文件，然后下载 https://endlesscheng.gitee.io/public/js/majsoul/code-zh.js 把文件名改成 code.js 替换之。
> > 不需要安装任何插件。
> 
> 多谢！另外，我似乎在之前某个JS文件里面看到了乳包内容（手动滑稽）。

@TianYaDY  那个是雀魂他们的测试代码，估计是用来测试关键词屏蔽的功能的。

**Comment by TianYaDY** [comment]
> > > > 大佬！可以稍微说下怎么和雀魂plus连用吗？雀魂plus没法安装谷歌的那些插件拓展，所以软件没有办法获取数据。
> > > 
> > > 
> > > @TianYaDY 搜索雀魂 plus 文件夹下的 code.js 文件，然后下载 https://endlesscheng.gitee.io/public/js/majsoul/code-zh.js 把文件名改成 code.js 替换之。
> > > 不需要安装任何插件。
> > 
> > 
> > 多谢！另外，我似乎在之前某个JS文件里面看到了乳包内容（手动滑稽）。
> 
> @TianYaDY 那个是雀魂他们的测试代码，估计是用来测试关键词屏蔽的功能的。

哈哈，原来如此。

**Comment by Con6924** [comment]
似乎雀魂plus2.0版本并没有code.js文件，想问一下有解决方案嘛？

**Comment by EndlessCheng** [comment]
> 似乎雀魂plus2.0版本并没有code.js文件，想问一下有解决方案嘛？

不会没有的，你可以用全局搜索看看，应该在某个文件夹下。

**Comment by Con6924** [comment]
看了一下项目，应该是雀魂plus2.0更改了打包方式。

> 现在默认启用 asar 打包，这意味着现在你不能以任何形式修改 雀魂 Plus 自带的源码了。
值得注意的是，可能有人之前是为了删除 雀魂 Plus 自带的某些 模组 / 插件 / 工具而修改其自带的源码。现在，雀魂 Plus 自带的内容会在第一次启动时复制到用户目录（appData）。在雀魂 Plus 资源管理器的界面内即可删除，不需要修改原目录了。 此举大大增加了雀魂 Plus 的安全性。在下面的破坏性更新中也有这一方面的内容。

这样的打包方式下在Release的版本中确实找不到code.js。

**Comment by EndlessCheng** [comment]
> 看了一下项目，应该是雀魂plus2.0更改了打包方式。
> 
> > 现在默认启用 asar 打包，这意味着现在你不能以任何形式修改 雀魂 Plus 自带的源码了。
> > 值得注意的是，可能有人之前是为了删除 雀魂 Plus 自带的某些 模组 / 插件 / 工具而修改其自带的源码。现在，雀魂 Plus 自带的内容会在第一次启动时复制到用户目录（appData）。在雀魂 Plus 资源管理器的界面内即可删除，不需要修改原目录了。 此举大大增加了雀魂 Plus 的安全性。在下面的破坏性更新中也有这一方面的内容。
> 
> 这样的打包方式下在Release的版本中确实找不到code.js。

我记得code.js不是源码的一部分，你在启动plus之后看看有没有下载code.js到某个文件夹下，全局搜索应该能找到。

**Comment by MyDayaa** [comment]
> 看了一下项目，应该是雀魂plus2.0更改了打包方式。
> 
> > 现在默认启用 asar 打包，这意味着现在你不能以任何形式修改 雀魂 Plus 自带的源码了。
> > 值得注意的是，可能有人之前是为了删除 雀魂 Plus 自带的某些 模组 / 插件 / 工具而修改其自带的源码。现在，雀魂 Plus 自带的内容会在第一次启动时复制到用户目录（appData）。在雀魂 Plus 资源管理器的界面内即可删除，不需要修改原目录了。 此举大大增加了雀魂 Plus 的安全性。在下面的破坏性更新中也有这一方面的内容。
> 
> 这样的打包方式下在Release的版本中确实找不到code.js。

现在在AppData目录下了
