### ISSUE TITLE
Installed program is not working

### ISSUE THREAD

**Issue by TomWithCode** [EndlessCheng/mahjong-helper#56]
I'm sorry for English, my Chinese is not good.

I followed all steps from the readme, but still, the software is not working for me.

1. Certificate checking
![image](https://user-images.githubusercontent.com/20135279/60931078-e89a8b00-a2ea-11e9-97fc-fbc86ad56802.png)

2. Header extension
![image](https://user-images.githubusercontent.com/20135279/60931095-f819d400-a2ea-11e9-92bc-e79550a14ddb.png)

3. The program was run
![image](https://user-images.githubusercontent.com/20135279/60931099-0667f000-a2eb-11e9-9594-4a88eaf8c429.png)

I restarted the browser and log in again to majsoul, started a new game and nothing happened in helper. I still can see the only initial message from #3 step.

The same thing happens for tenhou.

Can you please, tell me what I missed?

**Comment by TomWithCode** [comment]
I don't know what happened, but after a couple of browsers restarts it started to work.

**Comment by EndlessCheng** [comment]
Seems weird. The only reason I know is your browser cached the old JS code that Header Editor tried to replace.

The Helper is still in development, any questions are welcome.
