### ISSUE TITLE
一直显示初始界面

### ISSUE THREAD

**Issue by ouuan** [EndlessCheng/mahjong-helper#57]
![](https://i.loli.net/2019/07/10/5d25f68c2d5af60310.png)

![](https://i.loli.net/2019/07/10/5d25f68d65ed863562.png)

按照 README 安装完成，已经多次尝试重启浏览器与程序，一直是这个界面。

**Comment by EndlessCheng** [comment]
@ouuan  输入 `chrome://flags/#allow-insecure-localhost` 之后的界面能截图看看吗

**Comment by ouuan** [comment]
> @ouuan 输入 `chrome://flags/#allow-insecure-localhost` 之后的界面能截图看看吗

好像把卡巴斯基关掉就好了..,

**Comment by ouuan** [comment]
刚刚提 issue 前想着应该不会是杀软的问题就没试..

**Comment by ouuan** [comment]
![](https://i.loli.net/2019/07/10/5d25f8473b75d87091.png)

**Comment by EndlessCheng** [comment]
对于 CORS 的问题，可以试试安装浏览器插件 [CORS Unblock](https://chrome.google.com/webstore/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino/related)。
