### ISSUE TITLE
偶现证书异常

### ISSUE THREAD

**Issue by EndlessCheng** [EndlessCheng/mahjong-helper#59]
即使浏览器允许了本地证书，但还是偶尔会弹出证书异常的提示。

实际该报错不会对助手接收处理数据造成影响。

可以尝试复现该问题，或定制 echo 的stdlog 来屏蔽该报错。

**Comment by uyaddayu** [comment]
现在上不去了吧（如果开了的话

**Comment by EndlessCheng** [comment]
fixed by modify stdlog
