### ISSUE TITLE
本地https怎么实现

### ISSUE THREAD

**Issue by endlessWar** [EndlessCheng/mahjong-helper#6]
阿里云的申请localhost，没法通过ca安全审核。使用openssl卡在了
运行“nmake -f ms \ ntdll.mak”命令，发现出现问题，
“ms \ uplink.c（11）：致命错误C1083：不能打开包含文件：'windows.h'：  
没有这样的文件或目录NMAKE：致命错误U1077：'cl'：返回代码'0x2'停止。
运行vcvars32.bat和vcvars64.bat没有用
想问一下您是怎么实现访问本地使用HTTPS协议的

**Comment by endlessWar** [comment]
本地https实现：安装vs，注意安装Windows sdk 包；安装perl；按照openssl提示安装openssl；生成本地证书；安装nginx，开启本地https服务器，代理到12121端口

**Comment by ayssia** [comment]
请问nginx.conf是怎样配置的，这样好像不对？
`    server {
        listen       12121 ssl;
        server_name  localhost;

        ssl_certificate      test.crt;
        ssl_certificate_key  test.pem;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
            root   html;
            index  index.html index.htm;
        }
    }`

**Comment by EndlessCheng** [comment]
@endlessWar @ayssia  可以不要 Nginx 的，该功能近期内会和雀魂的数据解析一并发布
