### ISSUE TITLE
后期输出过慢，跟不上打牌速度

### ISSUE THREAD

**Issue by Simpson561** [EndlessCheng/mahjong-helper#60]
RT

**Comment by EndlessCheng** [comment]
请提供你的操作系统版本和CPU参数

**Comment by Simpson561** [comment]
Windows10 Ver1809 17763.253
机子属于学校的毒瘤机，CPU Intel Core i3-4160 3.6GHz

**Comment by EndlessCheng** [comment]
我没在i3上测试过，应该是CPU性能不足导致。助手在i5及以上的CPU上是即时反馈的。
算法上来说确实需要大量运算，我后续考虑看看能否通过某种剪枝策略来减少运算量。
