### ISSUE TITLE
请教下输出何切排序的逻辑是什么？

### ISSUE THREAD

**Issue by penguincwarrior** [EndlessCheng/mahjong-helper#61]
![1](https://user-images.githubusercontent.com/3872795/65145542-6518bb00-da4c-11e9-99f0-346c122d21cf.JPG)
![2](https://user-images.githubusercontent.com/3872795/65145543-6649e800-da4c-11e9-809a-eeef273da401.JPG)
如图所示，这里第一建议是切5p，可是切5p无论在何种情况下都比切1s差吧？除非做全带（笑）
作者是根据什么数据对何切进行排序的呢？

**Comment by EndlessCheng** [comment]
1s 好。
算法还在改进中，感谢提供数据！
