### ISSUE TITLE
回看牌谱的时候如果停顿太久或者重复前后去看的话没法分析

### ISSUE THREAD

**Issue by zhengye1** [EndlessCheng/mahjong-helper#67]
回看牌谱的时候有时候点左右键点多了，点到自己回合的时候，分析就分析不出来了，然而在其他人的回合的时候就会开始猜我手牌

**Comment by EndlessCheng** [comment]
感谢反馈。

我复现出这个问题了，雀魂的 JS 更新了左右键的逻辑，这会错误地在显示打牌动画时也会发送消息给助手。

**Comment by EndlessCheng** [comment]
修复中。

**Comment by EndlessCheng** [comment]
已修复。请重新载入网页。
