### ISSUE TITLE
部分bug

### ISSUE THREAD

**Issue by endlessWar** [EndlessCheng/mahjong-helper#7]
在实际体验中遇到的部分bug：
1.没有役牌规则，当我手上有19牌一向听时，能鸣牌时会提示我已听牌，然而如果我鸣牌，根本没有役；
2.没法理解副露后的牌型，当我有副露时，在推荐安全牌和切牌时会推荐我打1z，而我手上没有1z；
3.没法理解鸣牌时，手中剩余的牌，如我手中剩余1234p113z，在上家打出1p时会推荐我切3z听1p1z，然而如果我鸣牌了，手中剩下的牌型为14p11z，无法听牌

**Comment by endlessWar** [comment]
以上bug发现于天凤

**Comment by EndlessCheng** [comment]
感谢反馈！

1的话，无役判断其实是一个比较复杂的事情，后续会添加相关支持，副露提示仅供参考
2和3是代码逻辑上对于副露简化成一组刻子了，后续会对项目进行重构来完善副露相关的牌效、弃和判断

**Comment by toaruI** [comment]
有时候在某些牌型下会打印出非常多的紧张或者是改良，副露了之后特别容易发生

没来及截图，有了截图后会补上

另外关于副露好像还是有点小bug会提示打出不存在的字牌之类的，不过不是很影响

**Comment by EndlessCheng** [comment]
@toaruI   请问使用的版本号是多少？

**Comment by toaruI** [comment]
> @toaruI 请问使用的版本号是多少？

是之前0.1的版本，刚po了issure然后发现更新挺多了，准备重新下然后试试看

然后就遇到了另一个issure的问题

**Comment by EndlessCheng** [comment]
添加无役提醒：[v0.2.2](https://github.com/EndlessCheng/mahjong-helper/releases/tag/v0.2.2)
