### ISSUE TITLE
OC跟NC能同时存在么？

### ISSUE THREAD

**Issue by zhengye1** [EndlessCheng/mahjong-helper#70]
![image](https://user-images.githubusercontent.com/5428784/75393624-7c41bb80-58bc-11ea-9689-7edc45b99eba.png)
比如这个，helper推出来9p是NC也是OC
牌谱在这：雀魂牌谱: https://www.majsoul.com/1/?paipu=200227-b5997a9a-beb4-4b23-ab9b-9c12db8f4a94_a91653286

**Comment by EndlessCheng** [comment]
不会的，是NC的就不会去判断OC了

**Comment by EndlessCheng** [comment]
我看你这一手打了9p，在没有型听机会的情况下应尽量避免河底，选择对两家都安全的3s比较好

**Comment by zhengye1** [comment]
现在才看到你的回复，当初是因为看到这个说NC是9p，OC也是9p，然后我自庄想保庄就打了9p就试了一把NC打9p结果点了河底2333
