### ISSUE TITLE
echo: http: TLS handshake error from [::1]:50064: remote error: tls: unknown certificate

### ISSUE THREAD

**Issue by lilithes** [EndlessCheng/mahjong-helper#71]
已选择 - 雀魂（水晶杠杠版）
echo: http: TLS handshake error from [::1]:50064: remote error: tls: unknown certificate
您的账号 ID 为 **********，该数字为雀魂服务器账号数据库中的 ID，该值越小表示您的注册时间越早

这是为啥呀

**Comment by EndlessCheng** [comment]
先开局人机确认能否正常运行。若能则忽略该消息。

若不能正常运行，请确认安装说明第二步设置正确。

**Comment by jackjieYYY** [comment]
若不能正常运行，请确认：

是否按安装步骤正确安装
尝试安装 CORS Unblock
杀软限制了浏览器，导致数据无法发送给本地运行的助手


以上三点均已确认正确安装。但仍然提示 错误: remote error: tls: unknown certificate

目前唯一解决方法是清空浏览器缓存和强制F5刷新。但是下次打开雀魂就失效，只能再次清空缓存和F5强制刷新。

**Comment by EndlessCheng** [comment]
> 若不能正常运行，请确认：
> 
> 是否按安装步骤正确安装
> 尝试安装 CORS Unblock
> 杀软限制了浏览器，导致数据无法发送给本地运行的助手
> 
> 以上三点均已确认正确安装。但仍然提示 错误: remote error: tls: unknown certificate
> 
> 目前唯一解决方法是清空雀魂网站的cookie。但是下次打开雀魂就失效，只能再次清空和F5强制刷新。

已修复。如仍然遇到此问题请在下方回复。

**Comment by jackjieYYY** [comment]
> > 若不能正常运行，请确认：
> > 是否按安装步骤正确安装
> > 尝试安装 CORS Unblock
> > 杀软限制了浏览器，导致数据无法发送给本地运行的助手
> > 以上三点均已确认正确安装。但仍然提示 错误: remote error: tls: unknown certificate
> > 目前唯一解决方法是清空雀魂网站的cookie。但是下次打开雀魂就失效，只能再次清空和F5强制刷新。
> 
> 已修复，请清除一次 cookie 以重新载入。如仍然遇到此问题请在下方回复。

谢谢作者维护。程序可以正常使用。

**Comment by SQRPI** [comment]
清除cookie后仍然提示 `remote error: tls: unknown certificate`
已按照上面步骤确认, 无法解决问题,

**Comment by v1xerunt** [comment]
如果使用了SwitchyOmega等代理软件时会提示tls unkown certificate，需要注意关闭

**Comment by Celaeno1017** [comment]
按上述步骤操作和清除cookie后仍然提示 remote error: tls: unknown certificate。

**Comment by EndlessCheng** [comment]
@Celaeno1017  首先确认 chrome://flags/#allow-insecure-localhost 是否启用。

或者尝试打开 [https://localhost:12121](https://localhost:12121)，选择高级-继续前往，然后再打开雀魂页面。

**Comment by Asher23Sync** [comment]
enable了证书，扩展也按提示安装下载好了，打开助手还是显示
![OLVDF{Q59T$R4R}Z}$~(SG4](https://user-images.githubusercontent.com/97614980/149167603-a9e88b5e-9590-4f4b-97e5-32c10f9dbef7.png)
请问该如何解决？

**Comment by EndlessCheng** [comment]
试试右键用管理员打开。

一般是不需要这样打开的，可能是您电脑上设置了某些东西。

**Comment by Asher23Sync** [comment]
> 

谢谢，是系统屏蔽了私人网络的权限，现在解决了

**Comment by weiwei007z** [comment]
> 若不能正常运行，请确认：
> 
> 是否按安装步骤正确安装 尝试安装 CORS Unblock 杀软限制了浏览器，导致数据无法发送给本地运行的助手
> 
> 以上三点均已确认正确安装。但仍然提示 错误: remote error: tls: unknown certificate
> 
> 目前唯一解决方法是清空雀魂网站的cookie。但是下次打开雀魂就失效，只能再次清空和F5强制刷新。

你好，我已经按照安装步骤完成了，但还是无法使用助手，CORS Unblock已经安装，最近更新的net网址也替换了，打开助手后如图
![微信图片_20220612220858](https://user-images.githubusercontent.com/107356744/173237351-12eb0548-d3b3-4e37-bdfc-ed2d4c5bf51a.png)

后面打开雀魂创建人机后也没有改变，依然是这个界面，我在想是不是我漏了下载source code.. 我只下载了上面的文件
![微信图片_20220612220946](https://user-images.githubusercontent.com/107356744/173237432-ed2d0a7b-9075-4b84-ade5-e83ed7f1c9e9.png)

请问我下载source code之后还需要什么操作嘛。。。

**Comment by a2604296366** [comment]
你好目前是这个情况 
![I% TFPK ~`T)_4~2Z@6XM73](https://github.com/EndlessCheng/mahjong-helper/assets/140870491/41c2454e-2f55-4d03-9ac3-a37157ac7d53)
但是由于右边的问题导致游戏进不去

**Comment by a2604296366** [comment]
> 你好目前是这个情况 ![I% TFPK `T)_42Z@6XM73](https://user-images.githubusercontent.com/140870491/256982165-41c2454e-2f55-4d03-9ac3-a37157ac7d53.png) 但是由于右边的问题导致游戏进不去

请问如何解决

**Comment by buiawpkgew1** [comment]
> 你好目前是这个情况 
> ![I% TFPK ~`T)_4~2Z@6XM73](https://github.com/EndlessCheng/mahjong-helper/assets/140870491/41c2454e-2f55-4d03-9ac3-a37157ac7d53)
> 但是由于右边的问题导致游戏进不去
> 

不能用了

**Comment by a2604296366** [comment]
> > 你好目前是这个情况 
> > ![I% TFPK ~`T)_4~2Z@6XM73](https://github.com/EndlessCheng/mahjong-helper/assets/140870491/41c2454e-2f55-4d03-9ac3-a37157ac7d53)
> > 但是由于右边的问题导致游戏进不去
> > 
> 
> 不能用了

为什么不能用了呢

**Comment by buiawpkgew1** [comment]
> > > 你好目前是这个情况 
> > > ![I% TFPK ~`T)_4~2Z@6XM73](https://github.com/EndlessCheng/mahjong-helper/assets/140870491/41c2454e-2f55-4d03-9ac3-a37157ac7d53)
> > > 但是由于右边的问题导致游戏进不去
> > > 
> > 
> > 不能用了
> 
> 为什么不能用了呢

不更新怎么用？

**Comment by a2604296366** [comment]
> > > > 你好目前是这个情况 
> > > > ![I% TFPK ~`T)_4~2Z@6XM73](https://github.com/EndlessCheng/mahjong-helper/assets/140870491/41c2454e-2f55-4d03-9ac3-a37157ac7d53)
> > > > 但是由于右边的问题导致游戏进不去
> > > > 
> > > 
> > > 不能用了
> > 
> > 为什么不能用了呢
> 
> 不更新怎么用？

😅

**Comment by Aixtan** [comment]
老师，请问一下现在还能用吗？

**Comment by Aixtan** [comment]
老师，请问一下现在还能用吗？为什么我按步骤安装完成后打开小助手没有读取到我游戏界面的信息？
![Uploading 屏幕截图 2024-10-18 001229.png…]()

**Comment by Aixtan** [comment]
老师，请问一下现在还能用吗？为什么我按步骤安装完成后打开小助手没有读取到我游戏界面的信息？
![Uploading 1.png…]()

**Comment by Aixtan** [comment]
![Uploading 1.png…]()
