### ISSUE TITLE
天凤web没反应

### ISSUE THREAD

**Issue by GHLG** [EndlessCheng/mahjong-helper#72]
登录天凤后界面没有任何显示
![微信截图_20200330154411](https://user-images.githubusercontent.com/58800684/77887573-651c3200-729d-11ea-9a2a-67e77bd3f5f7.png)

**Comment by EndlessCheng** [comment]
前段时间天凤更新到了https，需要更新重定向链接。
也就是将安装步骤第三步中的 `https://jianyan.me/js/mahjong-helper.json` 重新下载
