### ISSUE TITLE
输出界面优化

### ISSUE THREAD

**Issue by a69e** [EndlessCheng/mahjong-helper#75]
现在版本的输出界面是如果不是自己，则会切换到一个等待上下对家切牌的界面，这个界面其实对自己是没有任何帮助的。提一个建议：输出界面最好能保持停留在第一视角，这样在等待上下对家切牌的时候自己能有更加充裕的时间去细看每一种取舍的具体概率和役牌可能性，为下一轮自己切牌做更充分思想准备。

**Comment by EndlessCheng** [comment]
不是很清楚你的意思，在摸牌之前手上是 13 张牌，无法分析取舍

**Comment by a69e** [comment]
我的意思是，每一轮在我等待其他三家行动的时候，输出界面只是显示这三家的信息，而我自己牌型分析的那部分数据没有了。我明白在我没有摸第14张牌的时候是无法进行分析，但是我的意思是希望至少还有部分数据能始终显示，比如当前是几向听，各个进张牌还剩几张之类的，那么我就可以在等待其他家行动的时候依然可以观察自己牌型的情况和具体分析。至少比一个只显示其他三家摸切牌的等待界面有作用得多吧。

EndlessCheng <notifications@github.com> 于2020年4月15日周三 下午1:29写道：

**Comment by EndlessCheng** [comment]
我明白你的意思了，这是个不错的建议，我会考虑加入到后续的版本中的
