### ISSUE TITLE
建议使用jsdelivr cdn加快js加载速度。

### ISSUE THREAD

**Issue by soloopooo** [EndlessCheng/mahjong-helper#78]
反正我是用了jsdelivr加载（

**Comment by EndlessCheng** [comment]
感谢建议，我待会试试

**Comment by EndlessCheng** [comment]
感觉不是很合适，更新了 JS 文件后 jsDelivr 没有刷新缓存导致一直停留在旧版本

**Comment by soloopooo** [comment]
速度快是重点啊（

**Comment by EndlessCheng** [comment]
你可能没有理解我的意思，我修改的文件是会随着雀魂的更新而更新的，但是 jsDelivr 是有 CDN 缓存的，如果 CDN 缓存没有刷新的话，就无法和雀魂的 JS 更新同步了。

**Comment by soloopooo** [comment]
那转战gitee吧

**Comment by EndlessCheng** [comment]
我有空测试一下

**Comment by soloopooo** [comment]
可以，辛苦了

**Comment by soloopooo** [comment]
提示：码云gitee不会自动部署，更新后需要手动部署一次才能在网站上更新。

**Comment by EndlessCheng** [comment]
原来如此。试了一下效果拔群！

**Comment by EndlessCheng** [comment]
请在 Header Editor 的下载规则中填入 https://endlesscheng.gitee.io/public/mahjong-helper.json，导入新的重定向规则，以保证能得到及时的更新。
