### ISSUE TITLE
雀魂访问报错

### ISSUE THREAD

**Issue by endlessWar** [EndlessCheng/mahjong-helper#8]
服务器返回：invalid character '\x03' looking for beginning of value
客户端提示：bad Request 
![image](https://user-images.githubusercontent.com/47861644/53388288-77a2a880-39c5-11e9-8657-1c16a1af0428.png)
400

**Comment by EndlessCheng** [comment]
雀魂的部分还在开发中

**Comment by endlessWar** [comment]
> 雀魂的部分还在开发中

大佬您好，暂时是无法解析雀魂websocket中的数据么？

**Comment by EndlessCheng** [comment]
雀魂的数据格式我看懂了，待我有空把相关代码重构一下push上来

**Comment by endlessWar** [comment]
谢谢茄子！

**Comment by endlessWar** [comment]
![image](https://user-images.githubusercontent.com/47861644/53464258-8a2fe700-3a84-11e9-911e-ec3e029312be.png)
提示收到数据过长

**Comment by EndlessCheng** [comment]
@endlessWar  可以描述下是在做什么操作时报的错的吗

**Comment by endlessWar** [comment]
> @endlessWar 可以描述下是在做什么操作时报的错吗，本地是否开启了Nginx

本地开启了nginx，ssl nginx监听了12120端口，雀魂将数据发送到12120端口，nginx转发到12121端口，然后就报错了

**Comment by endlessWar** [comment]
![image](https://user-images.githubusercontent.com/47861644/53470344-4c3ebd00-3a9c-11e9-88a8-54e7d9d5c0ca.png)

nginx配置如上，在code.js中将数据发送到了12120

**Comment by EndlessCheng** [comment]
@endlessWar  Nginx 不需要的，关掉试试
