### ISSUE TITLE
开启Header Editor后天凤不能加载音乐和字体

### ISSUE THREAD

**Issue by xeacra** [EndlessCheng/mahjong-helper#80]
控制台报错如下
Access to XMLHttpRequest at 'https://cdn.tenhou.net/3/snd/03.wav' (redirected from 'https://tenhou.net/3/snd/03.wav') from origin 'https://tenhou.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
cdn.tenhou.net/3/snd/03.wav:1

**Comment by EndlessCheng** [comment]
已修复，请刷新页面（或清空缓存并硬性加载）
