### ISSUE TITLE
运行mahjong-helper.exe有无法显示的字符

### ISSUE THREAD

**Issue by cj0424** [EndlessCheng/mahjong-helper#86]
![1593402174(1)](https://user-images.githubusercontent.com/48773180/85970672-23348200-b999-11ea-8210-d8238f2beffe.png)
如图，在运行mahjong-helper.exe有字符无法显示，请问应该如何解决这种情况

**Comment by EndlessCheng** [comment]
可能是操作系统语言的问题或者你之前改过 cmd 的设置。
可以看看 https://www.jianshu.com/p/16ad2dbba42b 这个
