### ISSUE TITLE
大佬！可以添加对雀魂plus的支持吗？

### ISSUE THREAD

**Issue by TianYaDY** [EndlessCheng/mahjong-helper#89]
非常喜欢这个软件，但很可惜，没有对雀魂plus的支持，雀魂plus应该也是使用chrome内核的，希望大佬添加一下支持。
指路牌：https://github.com/MajsoulPlus/majsoul-plus

**Comment by EndlessCheng** [comment]
感谢使用。参见 #53，如有问题可在该 Issue 下回复。

**Comment by TianYaDY** [comment]
感谢大佬！
