### ISSUE TITLE
用go get生成的助手提示内部错误

### ISSUE THREAD

**Issue by undeadfoxx** [EndlessCheng/mahjong-helper#92]
浏览器设置好只后用go get生成的助手对局中提示内部错误：[StrToTile34]参数错误：
请问这是什么原因呀？

**Comment by EndlessCheng** [comment]
天凤还是雀魂？

**Comment by undeadfoxx** [comment]
> 浏览器设置好只后用go get生成的助手对局中提示内部错误：[StrToTile34]参数错误：
> 请问这是什么原因呀？



> 天凤还是雀魂？

是雀魂。

**Comment by EndlessCheng** [comment]
这种情况是否一定出现，出现的话有特定的条件吗？

之前遇到过因为网络问题，导致助手没有接受到某些信息。

**Comment by undeadfoxx** [comment]
> 这种情况是否一定出现，出现的话有特定的条件吗？
> 
> 之前遇到过因为网络问题，导致助手没有接受到某些信息。

我感觉是我go get生成的助手程序有问题，只有9.3M。我看releases的助手程序是16.7M。
但是我重新用go get生成了好几次都是这样。是否现在只能下载releases里的程序不能用go get生成了呀？

**Comment by EndlessCheng** [comment]
能正常运行就是没问题的。

releases 中的二进制文件是用 `go build` 编译的，我没有加上 `-ldflags=-s`，所以会包含一些额外的 debug 内容，大小会大一些。

**Comment by undeadfoxx** [comment]
> 能正常运行就是没问题的。
> 
> releases 中的二进制文件是用 `go build` 编译的，我没有加上 `-ldflags=-s`，所以会包含一些额外的 debug 内容，大小会大一些。

我刚试了下，用releases里下载的程序可以正常运行对局也正常，但是go get的生成的只要一对局就会提示内部错误：[StrToTile34]参数错误。不过两者版本应该是一样的吧，我用releases下载的好了~感谢！

**Comment by EndlessCheng** [comment]
刚才试了一下，执行 `go get -u -v github.com/EndlessCheng/mahjong-helper/...` 后，生成的助手是能正常处理游戏信息的。

从文件大小上来看，我猜测你可能生成的是一个旧版本的助手文件，导致处理游戏信息失败。

**Comment by undeadfoxx** [comment]
> 刚才试了一下，执行 `go get -u -v github.com/EndlessCheng/mahjong-helper/...` 后，生成的助手是能正常处理游戏信息的。
> 
> 从文件大小上来看，我猜测你可能生成的是一个旧版本的助手文件，导致处理游戏信息失败。

感谢，不知道为什么我试了几次生成的都是这个旧版的。不折腾了，老老实实用releases下载的啦。谢谢~
