### ISSUE TITLE
在助手不能选择"0天凤"

### ISSUE THREAD

**Issue by marviswang** [EndlessCheng/mahjong-helper#93]
日本麻将助手 v0.2.7b (by EndlessCheng)
使用说明：https://github.com/EndlessCheng/mahjong-helper/blob/master/README.md
问题反馈：https://github.com/EndlessCheng/mahjong-helper/issues
吐槽群：375865038

请输入数字，以选择对应的平台：
0 - 天凤
1 - 雀魂
0
---------------------------------------------------------------------------------------------------------
请问是不是然后按“enter”？
按了以后助手就自己退出了

**Comment by EndlessCheng** [comment]
是 Windows 系统吗？

可能是你电脑上的 `cls` 命令异常，无法清除界面上的文字。

可以试试 win+R 后输入 cmd，然后在界面上按几次回车后，输入 `cls` 后看看是否会清除文字。

**Comment by marviswang** [comment]
谢谢，原来我忘记把助手放桌面
