### ISSUE TITLE
用的chrome，貌似日服又卡住了...

### ISSUE THREAD

**Issue by zhengye1** [EndlessCheng/mahjong-helper#94]
7月份有人报告这个bug，然而我今天试了下他又卡住了...
![image](https://user-images.githubusercontent.com/5428784/99140644-96215b00-2611-11eb-85e0-0119adc78e62.png)
关掉header啥问题都没有...

**Comment by EndlessCheng** [comment]
已修复，请刷新页面

**Comment by zhengye1** [comment]
我刚试了一下还是卡在了登陆画面...

**Comment by EndlessCheng** [comment]
如果仍然卡住请尝试清空缓存刷新
